const $=id=>document.getElementById(id);
let session=null,addresses=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const msg=(id,text)=>{const el=$(id);if(el)el.textContent=text||""};
const guestCount=()=>{try{const c=JSON.parse(localStorage.getItem("apnaCart")||"[]");return Array.isArray(c)?c.reduce((s,x)=>s+(Number(x?.qty)||0),0):0}catch{return 0}};
function resetAddress(){$("addressForm").reset();$("addressId").value="";$("cancelAddress").hidden=true}
function fillAddress(a){$("addressId").value=a.id;$("addressName").value=a.full_name||"";$("addressPhone").value=a.phone||"";$("addressLine").value=a.address_line||"";$("addressCity").value=a.city||"";$("addressState").value=a.state||"";$("addressPincode").value=a.pincode||"";$("addressDefault").checked=!!a.is_default;$("cancelAddress").hidden=false}
async function loadAddresses(){
 const r=await apnaSupabase.from("addresses").select("id,full_name,phone,address_line,city,state,pincode,is_default,created_at").eq("user_id",session.user.id).order("is_default",{ascending:false}).order("created_at",{ascending:true});
 if(r.error){msg("addressMessage",r.error.message);return}
 addresses=r.data||[];
 $("addressList").innerHTML=addresses.length?addresses.map(a=>'<article class="address-card"><strong>'+esc(a.full_name)+(a.is_default?'<span class="default-badge">Default</span>':"")+'</strong><p>'+esc(a.address_line)+'<br>'+esc(a.city)+", "+esc(a.state)+" — "+esc(a.pincode)+"<br>Phone: "+esc(a.phone)+'</p><div class="address-actions"><button type="button" data-edit="'+esc(a.id)+'">Edit</button>'+(a.is_default?"":'<button type="button" data-default="'+esc(a.id)+'">Make default</button>')+'<button type="button" data-delete="'+esc(a.id)+'">Delete</button></div></article>').join(""):'<div class="address-card"><p>No saved addresses yet. Add your first delivery address above.</p></div>';
 $("addressList").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>fillAddress(addresses.find(a=>a.id===b.dataset.edit)));
 $("addressList").querySelectorAll("[data-default]").forEach(b=>b.onclick=async()=>{msg("addressMessage","Updating default…");const r=await apnaSupabase.rpc("set_default_address_secure",{p_address_id:b.dataset.default});if(r.error)msg("addressMessage",r.error.message);else{msg("addressMessage","Default address updated.");await loadAddresses()}});
 $("addressList").querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this saved address?"))return;msg("addressMessage","Deleting…");const r=await apnaSupabase.rpc("delete_address_secure",{p_address_id:b.dataset.delete});if(r.error)msg("addressMessage",r.error.message);else{msg("addressMessage","Address deleted.");await loadAddresses()}});
}
async function loadAccount(){
 const r=await apnaSupabase.auth.getSession();if(r.error)throw r.error;session=r.data.session;$("bagCount").textContent=guestCount();
 if(!session){$("accountStatus").textContent="Sign in to access your Apna Store account.";return}
 const p=await apnaSupabase.from("profiles").select("full_name,role,birthday,referral_code").eq("id",session.user.id).maybeSingle();if(p.error)throw p.error;
 const name=p.data?.full_name||session.user.user_metadata?.full_name||session.user.email;
 $("accountTitle").textContent="Welcome, "+esc(name)+".";$("accountStatus").textContent=session.user.email||"";
 $("profilePanel").hidden=false;$("addressPanel").hidden=false;$("profileName").value=p.data?.full_name||"";$("profileEmail").value=session.user.email||"";const birthdayInput=$("birthdayInput");if(birthdayInput)birthdayInput.value=p.data?.birthday||"";const codeEl=$("referralCode"),linkEl=$("referralLink");if(codeEl)codeEl.textContent=p.data?.referral_code||"—";if(linkEl)linkEl.value=p.data?.referral_code?location.origin+location.pathname.replace(/account\.html$/i,"auth.html")+"?ref="+encodeURIComponent(p.data.referral_code):"";const pendingRef=localStorage.getItem("apnaReferralCode");if(pendingRef){const rr=await apnaSupabase.rpc("claim_referral_code",{p_code:pendingRef});if(!rr.error||/already|first order/i.test(rr.error.message||""))localStorage.removeItem("apnaReferralCode")};
 const [o,w,n,wal]=await Promise.all([apnaSupabase.from("orders").select("id",{count:"exact",head:true}).eq("user_id",session.user.id),apnaSupabase.from("wishlists").select("id",{count:"exact",head:true}).eq("user_id",session.user.id),apnaSupabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",session.user.id).eq("is_read",false),apnaSupabase.rpc("get_wallet")]);
 if(o.error)throw o.error;if(w.error)throw w.error;if(n.error)throw n.error;if(wal.error)throw wal.error;$("orderCount").textContent=o.count||0;$("wishCount").textContent=w.count||0;$("notificationCount").textContent=n.count||0;const wallet=Array.isArray(wal.data)?wal.data[0]:wal.data;const walletEl=$("walletBalance");if(walletEl)walletEl.textContent="₹"+Number(wallet?.balance||0).toLocaleString("en-IN");
 $("accountNote").textContent="Your orders, wishlist and saved addresses are connected to your Apna Store account.";
 async function loadDeliveryPreferences(){const panel=$("deliveryPreferencesPanel");if(!panel)return;panel.hidden=false;const r=await apnaSupabase.rpc("get_customer_delivery_preferences");if(r.error){msg("deliveryPreferencesMessage",r.error.message);return}const d=r.data||{};$("preferredDeliveryTime").value=d.preferred_delivery_time||"";$("deliveryInstructions").value=d.delivery_instructions||"";$("safePlace").value=d.safe_place||"";$("alternateContactName").value=d.alternate_contact_name||"";$("alternateContactPhone").value=d.alternate_contact_phone||"";$("leaveAtDoor").checked=!!d.leave_at_door;const np=d.notification_preferences||{};const cats=["order","shipment","delivery","offers"];const chans=["in_app","email","sms","whatsapp"];const grid=$("notificationPreferenceGrid");grid.innerHTML=cats.map(c=>'<div class="choice"><strong>'+c.replace(/_/g," ").replace(/^./,x=>x.toUpperCase())+'</strong> '+chans.map(ch=>'<label style="display:inline-flex;gap:5px;margin:4px 8px"><input type="checkbox" data-np-cat="'+c+'" data-np-channel="'+ch+'" '+(np?.[c]?.[ch]!==false?'checked':'')+'> '+ch.replace(/_/g," ")+'</label>').join('')+'</div>').join('');}
 $("deliveryPreferencesForm")?.addEventListener("submit",async e=>{e.preventDefault();const phone=$("alternateContactPhone").value.trim();if(phone&&!/^\\d{10}$/.test(phone)){msg("deliveryPreferencesMessage","Alternate contact phone must be 10 digits.");return}msg("deliveryPreferencesMessage","Saving…");const r=await apnaSupabase.rpc("save_customer_delivery_preferences",{p_preferred_delivery_time:$("preferredDeliveryTime").value||null,p_delivery_instructions:$("deliveryInstructions").value.trim()||null,p_safe_place:$("safePlace").value.trim()||null,p_alternate_contact_name:$("alternateContactName").value.trim()||null,p_alternate_contact_phone:phone||null,p_leave_at_door:$("leaveAtDoor").checked});if(r.error){msg("deliveryPreferencesMessage",r.error.message);return}const np={};$("notificationPreferenceGrid").querySelectorAll("[data-np-cat]").forEach(x=>{np[x.dataset.npCat]??={};np[x.dataset.npCat][x.dataset.npChannel]=x.checked});for(const cat of Object.keys(np))for(const ch of Object.keys(np[cat])){const rr=await apnaSupabase.from("notification_preferences").upsert({user_id:session.user.id,category:cat,channel:ch,enabled:np[cat][ch],updated_at:new Date().toISOString()},{onConflict:"user_id,category,channel"});if(rr.error){msg("deliveryPreferencesMessage",rr.error.message);return}}msg("deliveryPreferencesMessage","Delivery and notification preferences saved.");});
 $("accountActions").innerHTML=((p.data?.role==="admin")?'<a class="primary-btn" href="admin.html">Admin Panel →</a>':"")+'<button class="primary-btn" id="signOut" type="button">Sign out →</button><a href="shop.html">Continue shopping</a>';
 $("signOut").onclick=async()=>{const s=await apnaSupabase.auth.signOut();if(s.error)msg("accountNote",s.error.message);else location.href="index.html"};await loadAddresses();await loadDeliveryPreferences();
}
$("profileForm").addEventListener("submit",async e=>{e.preventDefault();const full_name=$("profileName").value.trim();if(!full_name){msg("profileMessage","Please enter your name.");return}msg("profileMessage","Saving…");const r=await apnaSupabase.from("profiles").update({full_name}).eq("id",session.user.id);msg("profileMessage",r.error?r.error.message:"Profile saved.");if(!r.error)$("accountTitle").textContent="Welcome, "+esc(full_name)+"."});
$("addressForm").addEventListener("submit",async e=>{e.preventDefault();const phone=$("addressPhone").value.trim(),pincode=$("addressPincode").value.trim();if(!/^\d{10}$/.test(phone)){msg("addressMessage","Phone must be 10 digits.");return}if(!/^\d{6}$/.test(pincode)){msg("addressMessage","Pincode must be 6 digits.");return}const fields={full_name:$("addressName").value.trim(),phone,address_line:$("addressLine").value.trim(),city:$("addressCity").value.trim(),state:$("addressState").value.trim(),pincode};if(Object.values(fields).some(v=>!v)){msg("addressMessage","Please fill all address fields.");return}msg("addressMessage","Saving…");const id=$("addressId").value;let r=id?await apnaSupabase.from("addresses").update({...fields,is_default:$("addressDefault").checked}).eq("id",id).eq("user_id",session.user.id):await apnaSupabase.from("addresses").insert({...fields,user_id:session.user.id,is_default:$("addressDefault").checked});if(r.error){msg("addressMessage",r.error.message);return}if($("addressDefault").checked){let target=id;if(!target){const latest=await apnaSupabase.from("addresses").select("id").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(1).single();target=latest.data?.id}if(target){const d=await apnaSupabase.rpc("set_default_address_secure",{p_address_id:target});if(d.error){msg("addressMessage",d.error.message);return}}}msg("addressMessage","Address saved.");resetAddress();await loadAddresses()});
$("cancelAddress").onclick=()=>{resetAddress();msg("addressMessage","")};
loadAccount().catch(err=>{console.error("Account load failed:",err);$("accountStatus").textContent=err.message||"Could not load your account."});

const saveBirthday=$("saveBirthday");if(saveBirthday)saveBirthday.onclick=async()=>{const el=$("birthdayInput"),m=$("birthdayMessage");if(!el?.value){if(m)m.textContent="Please choose your birthday.";return}saveBirthday.disabled=true;if(m)m.textContent="Saving…";const r=await apnaSupabase.rpc("set_my_birthday",{p_birthday:el.value});if(m)m.textContent=r.error?r.error.message:"Birthday saved. Your annual birthday reward will be processed automatically.";saveBirthday.disabled=false};
const copyReferral=$("copyReferral");if(copyReferral)copyReferral.onclick=async()=>{const link=$("referralLink")?.value||"";const m=$("referralMessage");if(!link)return;if(navigator.clipboard)await navigator.clipboard.writeText(link);else{const el=$("referralLink");el.select();document.execCommand("copy")}if(m)m.textContent="Referral link copied."};
