const $=id=>document.getElementById(id);let session=null,addresses=[];
function esc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function resetAddress(){$("addressForm").reset();$("addressId").value="";$("cancelAddress").hidden=true}
async function loadAddresses(){const {data,error}=await apnaSupabase.from("addresses").select("*").eq("user_id",session.user.id).order("is_default",{ascending:false}).order("created_at",{ascending:true});if(error){$("addressList").innerHTML='<p class="checkout-note">Could not load saved addresses.</p>';return}addresses=data||[];$("addressList").innerHTML=addresses.length?addresses.map(a=>'<article class="address-card"><strong>'+esc(a.full_name)+'</strong>'+(a.is_default?'<span class="default-badge">Default</span>':"")+'<p>'+esc(a.address_line)+'<br>'+esc(a.city)+', '+esc(a.state)+' — '+esc(a.pincode)+'<br>'+esc(a.phone)+'</p><div class="address-actions"><button data-edit="'+a.id+'">Edit</button>'+(a.is_default?"":'<button data-default="'+a.id+'">Make default</button>')+'<button data-delete="'+a.id+'">Delete</button></div></article>').join(""):'<div class="empty-cart"><h3>No saved addresses.</h3><p>Add an address to make checkout faster.</p></div>';
$("addressList").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const a=addresses.find(x=>x.id===b.dataset.edit);$("addressId").value=a.id;$("addressName").value=a.full_name||"";$("addressPhone").value=a.phone||"";$("addressLine").value=a.address_line||"";$("addressCity").value=a.city||"";$("addressState").value=a.state||"";$("addressPincode").value=a.pincode||"";$("addressDefault").checked=!!a.is_default;$("cancelAddress").hidden=false});
$("addressList").querySelectorAll("[data-default]").forEach(b=>b.onclick=async()=>{const {error}=await apnaSupabase.rpc("set_default_address_secure",{p_address_id:b.dataset.default});if(error)alert(error.message);else loadAddresses()});
$("addressList").querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this saved address?"))return;const {error}=await apnaSupabase.rpc("delete_address_secure",{p_address_id:b.dataset.delete});if(error)alert(error.message);else loadAddresses()})}
$("profileForm").onsubmit=async e=>{e.preventDefault();const {error}=await apnaSupabase.from("profiles").update({full_name:$("profileName").value.trim()}).eq("id",session.user.id);$("profileMessage").textContent=error?.message||"Profile saved.";if(!error)$("accountTitle").textContent="Welcome, "+$("profileName").value.trim()+"."};
$("addressForm").onsubmit=async e=>{e.preventDefault();const phone=$("addressPhone").value.trim(),pin=$("addressPincode").value.trim();if(!/^\d{10}$/.test(phone)||!/^\d{6}$/.test(pin)){$("addressMessage").textContent="Enter a valid 10-digit phone number and 6-digit pincode.";return}const p={user_id:session.user.id,full_name:$("addressName").value.trim(),phone,address_line:$("addressLine").value.trim(),city:$("addressCity").value.trim(),state:$("addressState").value.trim(),pincode:pin,is_default:$("addressDefault").checked};let error;if($("addressId").value)({error}=await apnaSupabase.from("addresses").update(p).eq("id",$("addressId").value).eq("user_id",session.user.id));else({error}=await apnaSupabase.from("addresses").insert(p));$("addressMessage").textContent=error?.message||"Address saved.";if(!error){resetAddress();loadAddresses()}};
$("cancelAddress").onclick=resetAddress;
(async()=>{const {data}=await apnaSupabase.auth.getSession();session=data.session;if(!session){$("accountStatus").textContent="Sign in to access your Apna Store account.";return}const {data:p}=await apnaSupabase.from("profiles").select("full_name").eq("id",session.user.id).maybeSingle();const name=p?.full_name||session.user.user_metadata?.full_name||session.user.email;$("accountTitle").textContent="Welcome, "+name+".";$("accountStatus").textContent=session.user.email;$("profilePanel").hidden=false;$("addressPanel").hidden=false;$("profileName").value=p?.full_name||"";$("profileEmail").value=session.user.email||"";const [{count:o},{count:w}]=await Promise.all([apnaSupabase.from("orders").select("id",{count:"exact",head:true}).eq("user_id",session.user.id),apnaSupabase.from("wishlists").select("id",{count:"exact",head:true}).eq("user_id",session.user.id)]);$("orderCount").textContent=o||0;$("wishCount").textContent=w||0;let c=[];try{c=JSON.parse(localStorage.getItem("apnaCart")||"[]")}catch{}$("bagCount").textContent=c.reduce((s,x)=>s+(Number(x?.qty)||0),0);$("accountActions").innerHTML='<button class="primary-btn" id="signOut">Sign out →</button><a href="shop.html">Continue shopping</a>';$("signOut").onclick=async()=>{await apnaSupabase.auth.signOut();location.href="index.html"};loadAddresses()})();