const $=id=>document.getElementById(id);
let session=null,addresses=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const msg=(id,text)=>{const el=$(id);if(el)el.textContent=text||""};
const guestCount=()=>{try{const c=JSON.parse(localStorage.getItem("apnaCart")||"[]");return Array.isArray(c)?c.reduce((s,x)=>s+(Number(x?.qty)||0),0):0}catch{return 0}};
function resetAddress(){$("addressForm").reset();$("addressId").value="";$("cancelAddress").hidden=true}
function fillAddress(a){$("addressId").value=a.id;$("addressName").value=a.full_name||"";$("addressPhone").value=a.phone||"";$("addressLine").value=a.address_line||"";$("addressCity").value=a.city||"";$("addressState").value=a.state||"";$("addressPincode").value=a.pincode||"";$("addressDefault").checked=!!a.is_default;$("cancelAddress").hidden=false}
async function loadAddresses(){
 const r=await apnaSupabase.from("addresses").select("id,full_name,phone,address_line,city,state,pincode,is_default,created_at").eq("user_id",session.user.id).order("is_default",{ascending:false}).order("created_at",{ascending:true});
 if(r.error){msg("addressMessage",r.error.message);return}
 addresses=r.data||[];
 $("addressList").innerHTML=addresses.length?addresses.map(a=>'<article class="address-card"><strong>'+esc(a.full_name)+(a.is_default?'<span class="default-badge">Default</span>':"")+'</strong><p>'+esc(a.address_line)+'<br>'+esc(a.city)+", "+esc(a.state)+" — "+esc(a.pincode)+"<br>Phone: "+esc(a.phone)+'</p><div class="address-actions"><button type="button" data-edit="'+esc(a.id)+'">Edit</button>'+(a.is_default?"":'<button type="button" data-default="'+esc(a.id)+'">Make default</button>')+'<button type="button" data-delete="'+esc(a.id)+'">Delete</button></div></article>').join(""):'<div class="address-card"><p>No saved addresses yet. Add your first delivery address above.</p></div>';
 $("addressList").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>fillAddress(addresses.find(a=>a.id===b.dataset.edit)));
 $("addressList").querySelectorAll("[data-default]").forEach(b=>b.onclick=async()=>{msg("addressMessage","Updating default…");const r=await apnaSupabase.rpc("set_default_address_secure",{p_address_id:b.dataset.default});if(r.error)msg("addressMessage",r.error.message);else{msg("addressMessage","Default address updated.");await loadAddresses()}});
 $("addressList").querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this saved address?"))return;msg("addressMessage","Deleting…");const r=await apnaSupabase.rpc("delete_address_secure",{p_address_id:b.dataset.delete});if(r.error)msg("addressMessage",r.error.message);else{msg("addressMessage","Address deleted.");await loadAddresses()}});
}
async function loadAccount(){
 const r=await apnaSupabase.auth.getSession();if(r.error)throw r.error;session=r.data.session;$("bagCount").textContent=guestCount();
 if(!session){$("accountStatus").textContent="Sign in to access your Apna Store account.";return}
 const p=await apnaSupabase.from("profiles").select("full_name,role").eq("id",session.user.id).maybeSingle();if(p.error)throw p.error;
 const name=p.data?.full_name||session.user.user_metadata?.full_name||session.user.email;
 $("accountTitle").textContent="Welcome, "+esc(name)+".";$("accountStatus").textContent=session.user.email||"";
 $("profilePanel").hidden=false;$("addressPanel").hidden=false;$("profileName").value=p.data?.full_name||"";$("profileEmail").value=session.user.email||"";
 const [o,w,n]=await Promise.all([apnaSupabase.from("orders").select("id",{count:"exact",head:true}).eq("user_id",session.user.id),apnaSupabase.from("wishlists").select("id",{count:"exact",head:true}).eq("user_id",session.user.id),apnaSupabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",session.user.id).eq("is_read",false)]);
 if(o.error)throw o.error;if(w.error)throw w.error;if(n.error)throw n.error;$("orderCount").textContent=o.count||0;$("wishCount").textContent=w.count||0;$("notificationCount").textContent=n.count||0;
 $("accountNote").textContent="Your orders, wishlist and saved addresses are connected to your Apna Store account.";
 $("accountActions").innerHTML='<a class="primary-btn" href="seller-onboarding.html">Become a seller →</a>'+((p.data?.role==="admin")?'<a class="primary-btn" href="admin.html">Admin Panel →</a>':"")+'<button class="primary-btn" id="signOut" type="button">Sign out →</button><a href="shop.html">Continue shopping</a>';
 $("signOut").onclick=async()=>{const s=await apnaSupabase.auth.signOut();if(s.error)msg("accountNote",s.error.message);else location.href="index.html"};await loadAddresses();
}
$("profileForm").addEventListener("submit",async e=>{e.preventDefault();const full_name=$("profileName").value.trim();if(!full_name){msg("profileMessage","Please enter your name.");return}msg("profileMessage","Saving…");const r=await apnaSupabase.from("profiles").update({full_name}).eq("id",session.user.id);msg("profileMessage",r.error?r.error.message:"Profile saved.");if(!r.error)$("accountTitle").textContent="Welcome, "+esc(full_name)+"."});
$("addressForm").addEventListener("submit",async e=>{e.preventDefault();const phone=$("addressPhone").value.trim(),pincode=$("addressPincode").value.trim();if(!/^\d{10}$/.test(phone)){msg("addressMessage","Phone must be 10 digits.");return}if(!/^\d{6}$/.test(pincode)){msg("addressMessage","Pincode must be 6 digits.");return}const fields={full_name:$("addressName").value.trim(),phone,address_line:$("addressLine").value.trim(),city:$("addressCity").value.trim(),state:$("addressState").value.trim(),pincode};if(Object.values(fields).some(v=>!v)){msg("addressMessage","Please fill all address fields.");return}msg("addressMessage","Saving…");const id=$("addressId").value;let r=id?await apnaSupabase.from("addresses").update({...fields,is_default:$("addressDefault").checked}).eq("id",id).eq("user_id",session.user.id):await apnaSupabase.from("addresses").insert({...fields,user_id:session.user.id,is_default:$("addressDefault").checked});if(r.error){msg("addressMessage",r.error.message);return}if($("addressDefault").checked){let target=id;if(!target){const latest=await apnaSupabase.from("addresses").select("id").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(1).single();target=latest.data?.id}if(target){const d=await apnaSupabase.rpc("set_default_address_secure",{p_address_id:target});if(d.error){msg("addressMessage",d.error.message);return}}}msg("addressMessage","Address saved.");resetAddress();await loadAddresses()});
$("cancelAddress").onclick=()=>{resetAddress();msg("addressMessage","")};
loadAccount().catch(err=>{console.error("Account load failed:",err);$("accountStatus").textContent=err.message||"Could not load your account."});
