const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let categoryRows=[],brandRows=[];
function setMessage(id,text,error=false){const el=$(id);if(el){el.textContent=text||"";el.className=error?"admin-message admin-error":"admin-message"}}
function resetForm(type){const p=type==="category"?["categoryId","categoryName","categorySort","categoryActive","categoryCancel"]:["brandId","brandName","brandSort","brandActive","brandCancel"];$(p[0]).value="";$(p[1]).value="";$(p[2]).value="0";$(p[3]).value="true";$(p[4]).hidden=true}
function renderCategories(){if(!categoryRows.length){setMessage("categories","No categories found.");return}$("categories").innerHTML='<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Products</th><th>Status</th><th>Order</th><th>Action</th></tr></thead><tbody>'+categoryRows.map(c=>'<tr><td><strong>'+esc(c.name)+'</strong></td><td>'+esc(c.slug)+'</td><td>'+Number(c.product_count||0)+'</td><td><span class="status-pill '+(c.is_active?"":"off")+'">'+(c.is_active?"Active":"Inactive")+'</span></td><td>'+Number(c.sort_order||0)+'</td><td><div class="admin-actions"><button class="admin-btn" data-edit-cat="'+c.id+'">Edit</button><button class="admin-btn danger" data-delete-cat="'+c.id+'">Delete</button></div></td></tr>').join("")+'</tbody></table></div>';$("categories").querySelectorAll("[data-edit-cat]").forEach(b=>b.onclick=()=>editCategory(categoryRows.find(x=>x.id===b.dataset.editCat)));$("categories").querySelectorAll("[data-delete-cat]").forEach(b=>b.onclick=()=>deleteCategory(b.dataset.deleteCat))}
function renderBrands(){if(!brandRows.length){setMessage("brands","No brands yet. Add the first brand above.");return}$("brands").innerHTML='<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Products</th><th>Status</th><th>Order</th><th>Action</th></tr></thead><tbody>'+brandRows.map(b=>'<tr><td><strong>'+esc(b.name)+'</strong></td><td>'+esc(b.slug)+'</td><td>'+Number(b.product_count||0)+'</td><td><span class="status-pill '+(b.is_active?"":"off")+'">'+(b.is_active?"Active":"Inactive")+'</span></td><td>'+Number(b.sort_order||0)+'</td><td><div class="admin-actions"><button class="admin-btn" data-edit-brand="'+b.id+'">Edit</button><button class="admin-btn danger" data-delete-brand="'+b.id+'">Delete</button></div></td></tr>').join("")+'</tbody></table></div>';$("brands").querySelectorAll("[data-edit-brand]").forEach(b=>b.onclick=()=>editBrand(brandRows.find(x=>x.id===b.dataset.editBrand)));$("brands").querySelectorAll("[data-delete-brand]").forEach(b=>b.onclick=()=>deleteBrand(b.dataset.deleteBrand))}
function editCategory(c){if(!c)return;$("categoryId").value=c.id;$("categoryName").value=c.name;$("categorySort").value=c.sort_order||0;$("categoryActive").value=String(!!c.is_active);$("categoryCancel").hidden=false;window.scrollTo({top:$("categoryForm").offsetTop-90,behavior:"smooth"})}
function editBrand(b){if(!b)return;$("brandId").value=b.id;$("brandName").value=b.name;$("brandSort").value=b.sort_order||0;$("brandActive").value=String(!!b.is_active);$("brandCancel").hidden=false;window.scrollTo({top:$("brandForm").offsetTop-90,behavior:"smooth"})}
async function loadCatalog(){const [c,b]=await Promise.all([apnaSupabase.rpc("admin_list_categories"),apnaSupabase.rpc("admin_list_brands")]);if(c.error){setMessage("categories",c.error.message,true);return}if(b.error){setMessage("brands",b.error.message,true);return}categoryRows=c.data||[];brandRows=b.data||[];renderCategories();renderBrands()}
async function saveCategory(e){e.preventDefault();const name=$("categoryName").value.trim();if(!name)return;const {error}=await apnaSupabase.rpc("admin_save_category",{p_category_id:$("categoryId").value||null,p_name:name,p_is_active:$("categoryActive").value==="true",p_sort_order:Math.max(0,Number($("categorySort").value)||0)});if(error){setMessage("categories",error.message,true);return}resetForm("category");await loadCatalog()}
async function saveBrand(e){e.preventDefault();const name=$("brandName").value.trim();if(!name)return;const {error}=await apnaSupabase.rpc("admin_save_brand",{p_brand_id:$("brandId").value||null,p_name:name,p_is_active:$("brandActive").value==="true",p_sort_order:Math.max(0,Number($("brandSort").value)||0)});if(error){setMessage("brands",error.message,true);return}resetForm("brand");await loadCatalog()}
async function deleteCategory(id){if(!confirm("Delete this category? If products use it, you will be asked to deactivate it instead."))return;const {error}=await apnaSupabase.rpc("admin_delete_category",{p_category_id:id});if(error){setMessage("categories",error.message,true);return}await loadCatalog()}
async function deleteBrand(id){if(!confirm("Delete this brand? If products use it, you will be asked to deactivate it instead."))return;const {error}=await apnaSupabase.rpc("admin_delete_brand",{p_brand_id:id});if(error){setMessage("brands",error.message,true);return}await loadCatalog()}
async function loadApplications(){const {data,error}=await apnaSupabase.rpc("admin_list_seller_applications",{p_status:null});if(error){setMessage("applications",error.message,true);return}const rows=data||[];$("pending").textContent=rows.filter(x=>x.status==="pending").length;$("approved").textContent=rows.filter(x=>x.status==="approved").length;$("rejected").textContent=rows.filter(x=>x.status==="rejected").length;if(!rows.length){setMessage("applications","No seller applications found.");return}$("applications").innerHTML='<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Applicant</th><th>Store</th><th>Business</th><th>Location</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>'+rows.map(a=>'<tr><td><strong>'+esc(a.full_name)+'</strong><br>'+esc(a.phone)+'</td><td>'+esc(a.store_name)+'</td><td>'+esc(a.business_type)+'</td><td>'+esc(a.city)+', '+esc(a.state)+'</td><td>'+esc(a.status)+(a.rejection_reason?'<br><small>'+esc(a.rejection_reason)+'</small>':"")+'</td><td>'+new Date(a.submitted_at).toLocaleDateString("en-IN")+'</td><td>'+((a.status==="pending")?'<div class="admin-actions"><button class="admin-btn primary" data-action="approved" data-id="'+a.id+'">Approve</button><button class="admin-btn" data-action="rejected" data-id="'+a.id+'">Reject</button></div>':'Reviewed')+'</td></tr>').join("")+'</tbody></table></div>';$("applications").querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>review(b.dataset.id,b.dataset.action))}
async function review(id,decision){let reason=null;if(decision==="rejected"){reason=prompt("Reason for rejection:");if(reason===null)return;if(!reason.trim()){alert("A rejection reason is required.");return}}const {error}=await apnaSupabase.rpc("admin_review_seller_application",{p_application_id:id,p_decision:decision,p_rejection_reason:reason});if(error){alert(error.message);return}await loadApplications()}
function campaignLocalValue(v){if(!v)return "";return new Date(v).toISOString().slice(0,16)}
function resetCampaign(){["campaignId","campaignName","campaignBadge","campaignHeadline","campaignDescription","campaignCtaUrl"].forEach(id=>$(id).value="");$("campaignCtaLabel").value="Shop now";$("campaignPlacement").value="homepage_deal";$("campaignSort").value="0";$("campaignActive").value="true";$("campaignStarts").value="";$("campaignEnds").value="";$("campaignCancel").hidden=true}
function renderCampaigns(){if(!window.campaignRows?.length){setMessage("campaigns","No marketing campaigns yet. Add the first promotion above.");return}$("campaigns").innerHTML='<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Placement</th><th>Status</th><th>Schedule</th><th>Order</th><th>Action</th></tr></thead><tbody>'+campaignRows.map(x=>'<tr><td><strong>'+esc(x.name)+'</strong><br><small>'+esc(x.headline)+'</small></td><td>'+esc(x.placement.replace("homepage_",""))+'</td><td><span class="status-pill '+(x.is_active?"":"off")+'">'+(x.is_active?"Active":"Inactive")+'</span></td><td>'+esc(x.starts_at?new Date(x.starts_at).toLocaleString("en-IN"):"Now")+' → '+esc(x.ends_at?new Date(x.ends_at).toLocaleString("en-IN"):"No end")+'</td><td>'+Number(x.sort_order||0)+'</td><td><div class="admin-actions"><button class="admin-btn" data-edit-campaign="'+x.id+'">Edit</button><button class="admin-btn danger" data-delete-campaign="'+x.id+'">Delete</button></div></td></tr>').join("")+'</tbody></table></div>';$("campaigns").querySelectorAll("[data-edit-campaign]").forEach(b=>b.onclick=()=>editCampaign(campaignRows.find(x=>x.id===b.dataset.editCampaign)));$("campaigns").querySelectorAll("[data-delete-campaign]").forEach(b=>b.onclick=()=>deleteCampaign(b.dataset.deleteCampaign))}
function editCampaign(x){if(!x)return;$("campaignId").value=x.id;$("campaignName").value=x.name||"";$("campaignBadge").value=x.badge||"";$("campaignHeadline").value=x.headline||"";$("campaignDescription").value=x.description||"";$("campaignCtaLabel").value=x.cta_label||"Shop now";$("campaignCtaUrl").value=x.cta_url||"shop.html";$("campaignPlacement").value=x.placement||"homepage_deal";$("campaignSort").value=x.sort_order||0;$("campaignActive").value=String(!!x.is_active);$("campaignStarts").value=campaignLocalValue(x.starts_at);$("campaignEnds").value=campaignLocalValue(x.ends_at);$("campaignCancel").hidden=false;window.scrollTo({top:$("campaignForm").offsetTop-90,behavior:"smooth"})}
async function loadCampaigns(){const {data,error}=await apnaSupabase.rpc("admin_list_marketing_campaigns");if(error){setMessage("campaigns",error.message,true);return}window.campaignRows=data||[];renderCampaigns()}
async function saveCampaign(e){e.preventDefault();const {error}=await apnaSupabase.rpc("admin_save_marketing_campaign",{p_campaign_id:$("campaignId").value||null,p_name:$("campaignName").value.trim(),p_badge:$("campaignBadge").value.trim()||null,p_headline:$("campaignHeadline").value.trim(),p_description:$("campaignDescription").value.trim()||null,p_cta_label:$("campaignCtaLabel").value.trim(),p_cta_url:$("campaignCtaUrl").value.trim(),p_placement:$("campaignPlacement").value,p_is_active:$("campaignActive").value==="true",p_starts_at:$("campaignStarts").value?new Date($("campaignStarts").value).toISOString():null,p_ends_at:$("campaignEnds").value?new Date($("campaignEnds").value).toISOString():null,p_sort_order:Math.max(0,Number($("campaignSort").value)||0)});if(error){setMessage("campaigns",error.message,true);return}resetCampaign();await loadCampaigns()}
async function deleteCampaign(id){if(!confirm("Delete this marketing campaign?"))return;const {error}=await apnaSupabase.rpc("admin_delete_marketing_campaign",{p_campaign_id:id});if(error){setMessage("campaigns",error.message,true);return}await loadCampaigns()}

let featureFlagRows=[];
function resetFeatureFlag(){["featureFlagId","featureFlagKey","featureFlagDescription"].forEach(id=>$(id).value="");$("featureFlagEnvironment").value="production";$("featureFlagRollout").value="0";$("featureFlagEnabled").checked=false;$("featureFlagClientVisible").checked=false;$("featureFlagCancel").hidden=true}
function renderFeatureFlags(){
 if(!featureFlagRows.length){$("featureFlagsList").innerHTML="<p>No feature flags yet.</p>";return}
 $("featureFlagsList").innerHTML='<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Key</th><th>Environment</th><th>Status</th><th>Rollout</th><th>Client</th><th>Action</th></tr></thead><tbody>'+featureFlagRows.map(x=>'<tr><td><strong>'+esc(x.flag_key)+'</strong><br><small>'+esc(x.description||"")+'</small></td><td>'+esc(x.environment)+'</td><td><span class="status-pill '+(x.enabled?"":"off")+'">'+(x.enabled?"Enabled":"Disabled")+'</span></td><td>'+Number(x.rollout_percent||0)+'%</td><td>'+(x.client_visible?"Yes":"No")+'</td><td><div class="admin-actions"><button class="admin-btn" data-edit-flag="'+x.id+'">Edit</button><button class="admin-btn danger" data-delete-flag="'+x.id+'">Delete</button></div></td></tr>').join("")+'</tbody></table></div>';
 $("featureFlagsList").querySelectorAll("[data-edit-flag]").forEach(b=>b.onclick=()=>editFeatureFlag(featureFlagRows.find(x=>x.id===b.dataset.editFlag)));
 $("featureFlagsList").querySelectorAll("[data-delete-flag]").forEach(b=>b.onclick=()=>deleteFeatureFlag(b.dataset.deleteFlag));
}
async function loadFeatureFlags(){const {data,error}=await apnaSupabase.rpc("admin_list_feature_flags");if(error){setMessage("featureFlagsMessage",error.message,true);return}featureFlagRows=data||[];setMessage("featureFlagsMessage","Feature flags loaded.");renderFeatureFlags()}
function editFeatureFlag(x){if(!x)return;$("featureFlagId").value=x.id;$("featureFlagKey").value=x.flag_key;$("featureFlagDescription").value=x.description||"";$("featureFlagEnvironment").value=x.environment;$("featureFlagRollout").value=x.rollout_percent||0;$("featureFlagEnabled").checked=!!x.enabled;$("featureFlagClientVisible").checked=!!x.client_visible;$("featureFlagCancel").hidden=false;window.scrollTo({top:$("featureFlagForm").offsetTop-90,behavior:"smooth"})}
async function saveFeatureFlag(e){e.preventDefault();const key=$("featureFlagKey").value.trim().toLowerCase();const rollout=Number($("featureFlagRollout").value);if(!key||!Number.isFinite(rollout)||rollout<0||rollout>100){setMessage("featureFlagsMessage","Enter a valid key and rollout from 0 to 100.",true);return}const {error}=await apnaSupabase.rpc("admin_save_feature_flag",{p_flag_id:$("featureFlagId").value||null,p_flag_key:key,p_description:$("featureFlagDescription").value.trim()||null,p_enabled:$("featureFlagEnabled").checked,p_environment:$("featureFlagEnvironment").value,p_rollout_percent:rollout,p_client_visible:$("featureFlagClientVisible").checked});if(error){setMessage("featureFlagsMessage",error.message,true);return}resetFeatureFlag();await loadFeatureFlags()}
async function deleteFeatureFlag(id){if(!confirm("Delete this feature flag?"))return;const {error}=await apnaSupabase.rpc("admin_delete_feature_flag",{p_flag_id:id});if(error){setMessage("featureFlagsMessage",error.message,true);return}await loadFeatureFlags()}

async function loadObservability(){
 const [s,l]=await Promise.all([apnaSupabase.rpc("admin_observability_summary"),apnaSupabase.rpc("admin_list_audit_logs",{p_limit:100})]);
 if(s.error){setMessage("auditLogsMessage",s.error.message,true);return}
 const x=s.data||{};
 $("observabilityCards").innerHTML='<div class="admin-stats-grid"><div class="admin-stat-card"><strong>'+Number(x.audit_events_24h||0)+'</strong><span>Audit events / 24h</span></div><div class="admin-stat-card"><strong>'+Number(x.analytics_events_24h||0)+'</strong><span>Analytics events / 24h</span></div><div class="admin-stat-card"><strong>'+Number(x.shipments_total||0)+'</strong><span>Total shipments</span></div><div class="admin-stat-card"><strong>'+Number(x.failed_shipments||0)+'</strong><span>Failed/RTO shipments</span></div><div class="admin-stat-card"><strong>'+Number(x.open_returns||0)+'</strong><span>Open returns</span></div></div>';
 if(l.error){setMessage("auditLogsMessage",l.error.message,true);return}
 const rows=l.data||[];
 $("auditLogsList").innerHTML=rows.length?'<div class="seller-table-wrap"><table class="admin-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+new Date(r.created_at).toLocaleString()+'</td><td>'+esc(r.actor_name||r.actor_id||"System")+'</td><td>'+esc(r.action)+'</td><td>'+esc(r.entity_type)+(r.entity_id?'<br><small>'+esc(r.entity_id)+'</small>':"")+'</td><td><code>'+esc(JSON.stringify(r.metadata||{}))+'</code></td></tr>').join("")+'</tbody></table></div>':'<p>No audit events yet.</p>';
 setMessage("auditLogsMessage","Showing "+rows.length+" recent audit events.");
}

function isoDate(d){return d.toISOString().slice(0,10)}
function money(v){return "₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
function renderAnalytics(a){const o=a.overview||{};const daily=a.daily_sales||[];const max=Math.max(1,...daily.map(x=>Number(x.sales||0)));const bars=daily.map(x=>'<div class="analytics-bar" style="height:'+Math.max(2,(Number(x.sales||0)/max)*160)+'px" title="'+esc(x.date)+': '+money(x.sales)+'"><small>'+esc(String(x.date).slice(5))+'</small></div>').join("");const statuses=(a.order_statuses||[]).map(x=>'<tr><td>'+esc(x.status)+'</td><td>'+Number(x.count||0)+'</td></tr>').join("")||'<tr><td colspan="2">No orders</td></tr>';const products=(a.top_products||[]).map(x=>'<tr><td>'+esc(x.product_name)+'</td><td>'+Number(x.quantity||0)+' · '+money(x.sales)+'</td></tr>').join("")||'<tr><td colspan="2">No product sales</td></tr>';$("analyticsContent").innerHTML='<div class="analytics-grid"><div class="admin-card"><span>Gross sales</span><strong>'+money(o.gross_sales)+'</strong></div><div class="admin-card"><span>Orders</span><strong>'+Number(o.orders||0)+'</strong></div><div class="admin-card"><span>Customers</span><strong>'+Number(o.customers||0)+'</strong></div><div class="admin-card"><span>Average order</span><strong>'+money(o.average_order_value)+'</strong></div><div class="admin-card"><span>Products sold</span><strong>'+Number(o.products_sold||0)+'</strong></div><div class="admin-card"><span>Delivered</span><strong>'+Number(o.delivered_orders||0)+'</strong></div><div class="admin-card"><span>Discounts</span><strong>'+money(o.discounts)+'</strong></div><div class="admin-card"><span>Returns requested</span><strong>'+Number(o.return_requests||0)+'</strong></div></div><div class="analytics-chart"><h3>Daily sales</h3><div class="analytics-bars">'+bars+'</div></div><div class="analytics-columns"><div><h3>Order status</h3><table class="analytics-table">'+statuses+'</table></div><div><h3>Top products</h3><table class="analytics-table">'+products+'</table></div></div><div class="section-note">Seller funnel: '+Number(a.seller_funnel?.applications||0)+' applications · '+Number(a.seller_funnel?.approved||0)+' approved · '+Number(a.seller_funnel?.active_sellers||0)+' active sellers.</div>';$("analyticsContent").hidden=false}
async function loadAnalytics(){const start=$("analyticsStart").value,end=$("analyticsEnd").value;if(!start||!end)return;const endExclusive=new Date(end+"T23:59:59.999Z");const {data,error}=await apnaSupabase.rpc("admin_get_analytics",{p_start_at:new Date(start+"T00:00:00.000Z").toISOString(),p_end_at:endExclusive.toISOString()});if(error){setMessage("analyticsMessage",error.message,true);$("analyticsContent").hidden=true;return}setMessage("analyticsMessage","Analytics updated.");renderAnalytics(data||{})}
function initAnalytics(){const end=new Date();const start=new Date(end);start.setUTCDate(start.getUTCDate()-29);$("analyticsStart").value=isoDate(start);$("analyticsEnd").value=isoDate(end);$("analyticsForm").addEventListener("submit",e=>{e.preventDefault();loadAnalytics()})}
async function boot(){const {data:s,error}=await apnaSupabase.auth.getSession();if(error||!s.session){location.href="auth.html";return}const {data:p}=await apnaSupabase.from("profiles").select("role").eq("id",s.session.user.id).single();if(!p||p.role!=="admin"){location.href="account.html";return}$("categoryForm").addEventListener("submit",saveCategory);$("featureFlagForm").addEventListener("submit",saveFeatureFlag);$("featureFlagCancel").onclick=resetFeatureFlag;$("refreshObservability").onclick=loadObservability;$("brandForm").addEventListener("submit",saveBrand);$("categoryCancel").onclick=()=>resetForm("category");$("brandCancel").onclick=()=>resetForm("brand");$("campaignForm").addEventListener("submit",saveCampaign);$("campaignCancel").onclick=resetCampaign;initAnalytics();await Promise.all([loadCatalog(),loadApplications(),loadCampaigns(),loadAnalytics(),loadFeatureFlags(),loadObservability()])}boot();