const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let role="",rows=[],products=[],categories=[];
function money(v){return"₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
function localValue(v){return v?new Date(v).toISOString().slice(0,16):""}
function setMsg(t,e=false){$("message").textContent=t||"";$("message").className="coupon-message"+(e?" coupon-error":"")}
function resetForm(){$("couponId").value="";$("code").value="";$("name").value="";$("discountType").value="percent";$("discountValue").value="";$("minOrder").value="0";$("maxDiscount").value="";$("usageLimit").value="";$("perUserLimit").value="1";$("startsAt").value="";$("expiresAt").value="";$("scope").value="all";$("firstOrder").checked=false;$("description").value="";$("active").checked=true;$("cancelEdit").hidden=true;$("formTitle").textContent="Create coupon";updateScope()}
function updateScope(){const s=$("scope").value;$("productsField").hidden=s!=="products";$("categoriesField").hidden=s!=="categories"}
function renderOptions(){ $("products").innerHTML=products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+(p.sku?' · '+esc(p.sku):"")+'</option>').join("");$("categories").innerHTML=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join("")}
function render(){const total=rows.reduce((s,x)=>s+Number(x.redemptions||0),0),discount=rows.reduce((s,x)=>s+Number(x.total_discount||0),0);$("statCoupons").textContent=rows.length;$("statActive").textContent=rows.filter(x=>x.is_active).length;$("statRedemptions").textContent=total;$("statDiscount").textContent=money(discount);if(!rows.length){$("list").innerHTML='<div class="coupon-message">No coupons found. Create the first real coupon above.</div>';return}
$("list").innerHTML='<table class="coupon-table"><thead><tr><th>Code</th><th>Discount</th><th>Scope</th><th>Limits</th><th>Status</th><th>Redemptions</th><th>Discount given</th><th>Action</th></tr></thead><tbody>'+rows.map(x=>'<tr><td><strong>'+esc(x.code)+'</strong><br><small>'+esc(x.name)+'</small></td><td>'+esc(x.discount_type==='percent'?Number(x.discount_value)+'%':money(x.discount_value))+(x.max_discount_amount?' · cap '+money(x.max_discount_amount):"")+'</td><td>'+esc(x.owner_type==='seller'?'Seller':'Platform')+' · '+esc(x.scope_type)+(x.first_order_only?' · First order':"")+'</td><td>Min '+money(x.min_order_amount)+'<br>'+((x.usage_limit??null)===null?'Unlimited':Number(x.usage_count)+' / '+Number(x.usage_limit))+' total<br>'+Number(x.per_user_limit)+' / customer</td><td><span class="pill '+(x.is_active?'':'off')+'">'+(x.is_active?'Active':'Inactive')+'</span><br><small>'+esc(new Date(x.starts_at).toLocaleDateString("en-IN"))+' → '+esc(x.expires_at?new Date(x.expires_at).toLocaleDateString("en-IN"):"No end")+'</small></td><td>'+Number(x.redemptions||0)+'</td><td>'+money(x.total_discount)+'</td><td><div class="row-actions"><button data-edit="'+x.id+'">Edit</button>'+(x.is_active?'<button class="danger" data-off="'+x.id+'">Deactivate</button>':"")+'</div></td></tr>').join("")+'</tbody></table>';
$("list").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(rows.find(x=>x.id===b.dataset.edit)));$("list").querySelectorAll("[data-off]").forEach(b=>b.onclick=()=>deactivate(b.dataset.off))}
function edit(x){if(!x)return;$("couponId").value=x.id;$("code").value=x.code;$("name").value=x.name;$("description").value=x.description||"";$("discountType").value=x.discount_type;$("discountValue").value=x.discount_value;$("minOrder").value=x.min_order_amount;$("maxDiscount").value=x.max_discount_amount??"";$("usageLimit").value=x.usage_limit??"";$("perUserLimit").value=x.per_user_limit;$("firstOrder").checked=!!x.first_order_only;$("startsAt").value=localValue(x.starts_at);$("expiresAt").value=localValue(x.expires_at);$("scope").value=x.scope_type;$("active").checked=!!x.is_active;updateScope();[...$("products").options].forEach(o=>o.selected=(x.product_ids||[]).includes(o.value));[...$("categories").options].forEach(o=>o.selected=(x.category_ids||[]).includes(o.value));$("formTitle").textContent="Edit coupon";$("cancelEdit").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
async function loadOptions(){const [p,c]=await Promise.all([apnaSupabase.from("products").select("id,name,sku").eq("status","active").order("name"),apnaSupabase.from("categories").select("id,name").eq("is_active",true).order("sort_order").order("name")]);if(p.error||c.error)throw p.error||c.error;products=p.data||[];categories=c.data||[];renderOptions()}
async function loadCoupons(){const {data,error}=await apnaSupabase.rpc("coupon_list");if(error)throw error;rows=data||[];render()}
async function save(e){e.preventDefault();const scope=$("scope").value,productIds=[...$("products").selectedOptions].map(o=>o.value),categoryIds=[...$("categories").selectedOptions].map(o=>o.value);const args={p_coupon_id:$("couponId").value||null,p_code:$("code").value.trim(),p_name:$("name").value.trim(),p_description:$("description").value.trim()||null,p_owner_type:role==="admin"?"platform":"seller",p_scope_type:scope,p_discount_type:$("discountType").value,p_discount_value:Number($("discountValue").value),p_min_order_amount:Number($("minOrder").value||0),p_max_discount_amount:$("maxDiscount").value===""?null:Number($("maxDiscount").value),p_usage_limit:$("usageLimit").value===""?null:Number($("usageLimit").value),p_per_user_limit:Number($("perUserLimit").value||1),p_first_order_only:$("firstOrder").checked,p_starts_at:$("startsAt").value?new Date($("startsAt").value).toISOString():new Date().toISOString(),p_expires_at:$("expiresAt").value?new Date($("expiresAt").value).toISOString():null,p_is_active:$("active").checked,p_product_ids:productIds,p_category_ids:categoryIds};setMsg("Saving…");const {error}=await apnaSupabase.rpc("coupon_save",args);if(error){setMsg(error.message,true);return}resetForm();setMsg("Coupon saved.");await loadCoupons()}
async function deactivate(id){if(!confirm("Deactivate this coupon? Existing order history will be preserved."))return;const {error}=await apnaSupabase.rpc("coupon_deactivate",{p_coupon_id:id});if(error){setMsg(error.message,true);return}await loadCoupons()}
async function boot(){const {data,error}=await apnaSupabase.auth.getSession();if(error||!data.session){location.href="auth.html";return}const {data:p,error:pe}=await apnaSupabase.from("profiles").select("role").eq("id",data.session.user.id).single();if(pe||!p||!["admin","seller"].includes(p.role)){location.href="account.html";return}role=p.role;$("title").textContent=role==="admin"?"Platform Coupons":"Seller Coupons";$("subtitle").textContent=role==="admin"?"Create platform, product/category and first-order coupons with real usage analytics.":"Create coupons for your own products with real usage analytics.";$("backLink").href=role==="admin"?"admin.html":"seller-dashboard.html";$("couponForm").addEventListener("submit",save);$("cancelEdit").onclick=resetForm;$("scope").addEventListener("change",updateScope);try{await loadOptions();await loadCoupons();setMsg("Ready.")}catch(e){setMsg(e.message||"Could not load coupon center.",true)}}boot();