const $=id=>document.getElementById(id);let user,role,variants=[],products={},movements=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>"₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2});
function msg(v,error=false){$("message").textContent=v||"";$("message").className=error?"message error":"message";}
function visible(){const q=$("search").value.trim().toLowerCase(),f=$("filter").value;return variants.filter(v=>{const p=products[v.product_id]||{},hay=(p.name+" "+(v.sku||"")+" "+(v.size||"")+" "+(v.color||"")).toLowerCase();const stock=Number(v.stock||0);return(!q||hay.includes(q))&&(f==="all"||(f==="low"&&stock>0&&stock<=5)||(f==="out"&&stock<=0)||(f==="healthy"&&stock>=6))})}
function render(){const list=visible();const low=variants.filter(v=>Number(v.stock||0)>0&&Number(v.stock||0)<=5).length,out=variants.filter(v=>Number(v.stock||0)<=0).length;$("variantCount").textContent=variants.length;$("lowCount").textContent=low;$("outCount").textContent=out;if(!list.length){$("panel").innerHTML='<div class="empty">No inventory matches this view.</div>';return}
$("panel").innerHTML='<table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Variant</th><th>Current stock</th><th>Adjust stock</th></tr></thead><tbody>'+list.map(v=>{const p=products[v.product_id]||{};const stock=Number(v.stock||0);return '<tr><td><strong>'+esc(p.name||"Unknown product")+'</strong></td><td>'+esc(v.sku||"—")+'</td><td>'+esc([v.size,v.color].filter(Boolean).join(" / ")||"Standard")+'</td><td class="'+(stock<=0?"out":stock<=5?"low":"")+'">'+stock+'</td><td><div class="adjust"><input type="number" class="delta" data-id="'+v.id+'" step="1" placeholder="+/- qty"><select class="reason" data-id="'+v.id+'"><option value="manual_adjustment">Manual</option><option value="restock">Restock</option><option value="correction">Correction</option><option value="return">Return</option></select><input class="note" data-id="'+v.id+'" maxlength="200" placeholder="Note (optional)"><button class="btn" data-adjust="'+v.id+'">Apply</button></div></td></tr>'}).join("")+'</tbody></table>';$("panel").querySelectorAll("[data-adjust]").forEach(b=>b.onclick=()=>adjust(b.dataset.adjust));}
async function adjust(id){const dEl=document.querySelector('.delta[data-id="'+id+'"]'),rEl=document.querySelector('.reason[data-id="'+id+'"]'),nEl=document.querySelector('.note[data-id="'+id+'"]');const delta=Number(dEl.value);if(!Number.isInteger(delta)||delta===0){msg("Enter a non-zero whole-number stock adjustment.",true);return}msg("Applying stock adjustment…");const{data,error}=await apnaSupabase.rpc("seller_adjust_inventory",{p_variant_id:id,p_delta:delta,p_reason:rEl.value,p_note:nEl.value.trim()||null});if(error){msg(error.message,true);return}msg("Stock updated to "+data+".");dEl.value="";nEl.value="";await loadInventory();}
async function loadInventory(){const{data:v,error}=await apnaSupabase.from("product_variants").select("id,product_id,size,color,sku,stock").order("created_at");if(error){msg(error.message,true);return}variants=v||[];const ids=[...new Set(variants.map(x=>x.product_id))];products={};if(ids.length){const{data:p,error:pe}=await apnaSupabase.from("products").select("id,name,status").in("id",ids);if(pe){msg(pe.message,true);return}(p||[]).forEach(x=>products[x.id]=x)}const{data:m}=await apnaSupabase.from("inventory_movements").select("id,product_variant_id,quantity_before,quantity_change,quantity_after,reason,note,created_at").order("created_at",{ascending:false}).limit(30);movements=m||[];renderHistory();render();}
function renderHistory(){if(!movements.length){$("history").innerHTML='<div class="empty">No stock movements recorded yet.</div>';return}$("history").innerHTML='<table class="table"><thead><tr><th>Time</th><th>Product / Variant</th><th>Before</th><th>Change</th><th>After</th><th>Reason</th><th>Note</th></tr></thead><tbody>'+movements.map(m=>{const v=variants.find(x=>x.id===m.product_variant_id),p=v?products[v.product_id]:null;return '<tr><td>'+new Date(m.created_at).toLocaleString("en-IN")+'</td><td>'+esc(p?.name||"Product")+' · '+esc(v?[v.size,v.color].filter(Boolean).join(" / ")||"Standard":"Variant")+'</td><td>'+m.quantity_before+'</td><td class="'+(m.quantity_change<0?"out":"")+'">'+(m.quantity_change>0?"+":"")+m.quantity_change+'</td><td>'+m.quantity_after+'</td><td>'+esc(m.reason)+'</td><td>'+esc(m.note||"—")+'</td></tr>'}).join("")+'</tbody></table>'}
$("search").oninput=render;$("filter").onchange=render;$("refresh").onclick=loadInventory;
async function boot(){const{data:s,error}=await apnaSupabase.auth.getSession();if(error||!s.session){location.href="auth.html";return}user=s.session.user;const{data:p}=await apnaSupabase.from("profiles").select("role").eq("id",user.id).single();if(!p||!["seller","admin"].includes(p.role)){location.href="account.html";return}role=p.role;await loadInventory();}boot();