const reviewProductId=new URLSearchParams(location.search).get("id");
const reviewEsc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stars=n=>{n=Math.max(0,Math.min(5,Number(n)||0));return "★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)};
const reviewStyle=()=>{if(document.getElementById("reviewPhase34Style"))return;const s=document.createElement("style");s.id="reviewPhase34Style";s.textContent=".product-reviews{margin-top:28px;padding:24px;border-top:1px solid #e5e1da}.reviews-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.review-average{display:grid;text-align:right;gap:2px}.review-average strong{font-size:28px}.review-average span,.review-stars{letter-spacing:.08em}.review-average small,.review-card small{color:#777}.review-form{display:grid;gap:10px;max-width:700px;margin:20px 0}.review-form label{display:grid;gap:6px;font-size:12px;font-weight:700;color:#555}.review-form input,.review-form textarea,.review-form select{padding:10px;border:1px solid #ddd;background:#fff;font:inherit}.review-list{display:grid;gap:10px}.review-card{border:1px solid #e5e1da;background:#fff;padding:14px}.review-card-top{display:flex;justify-content:space-between;gap:10px}.verified-review{display:inline-block;margin-left:8px;padding:3px 7px;border-radius:999px;background:#eef7ee;font-size:10px}.review-card h3{margin:8px 0 4px;font-size:15px}.review-card p{line-height:1.5}.review-images{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.review-images img{width:72px;height:72px;object-fit:cover;border:1px solid #ddd}.review-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.review-actions button{border:1px solid #ddd;background:#fff;padding:7px 10px;cursor:pointer}.review-response{margin-top:10px;padding:10px 12px;background:#faf9f6;border-left:3px solid #111}.review-response strong{font-size:12px}.review-report{display:none;margin-top:10px;padding:10px;background:#faf9f6}.review-report select,.review-report textarea{width:100%;padding:8px;border:1px solid #ddd;margin-top:6px}.review-message{font-size:12px;color:#666}.review-pending{font-size:12px;color:#777;margin-top:8px}.review-upload{font-size:12px;color:#666}";
document.head.appendChild(s)};
async function renderReviews(){
 const product=document.getElementById("product");if(!product||!reviewProductId)return;reviewStyle();
 const existing=document.getElementById("reviews");if(existing)existing.remove();
 const box=document.createElement("section");box.className="product-reviews";box.id="reviews";product.appendChild(box);
 const {data:rows,error}=await apnaSupabase.from("reviews").select("id,rating,title,body,created_at,verified_purchase,user_id,order_id,moderation_status").eq("product_id",reviewProductId).order("created_at",{ascending:false});
 if(error){box.innerHTML='<div class="reviews-empty">Reviews are temporarily unavailable.</div>';return}
 const reviews=rows||[],visible=reviews.filter(r=>r.moderation_status==="approved");
 const avg=visible.length?visible.reduce((s,r)=>s+Number(r.rating||0),0)/visible.length:0;
 const {data:{session}}=await apnaSupabase.auth.getSession();let eligible=[],ownPending=[];
 if(session){
   const q=await apnaSupabase.from("orders").select("id,order_number,order_items!inner(product_id)").eq("user_id",session.user.id).eq("delivery_status","delivered").eq("order_items.product_id",reviewProductId).order("created_at",{ascending:false});
   const mine=reviews.filter(r=>r.user_id===session.user.id);const used=new Set(mine.map(r=>r.order_id));ownPending=mine.filter(r=>r.moderation_status!=="approved");
   eligible=(q.data||[]).filter(o=>!used.has(o.id));
 }
 const {data:images}=visible.length?await apnaSupabase.from("review_images").select("review_id,storage_path").in("review_id",visible.map(r=>r.id)): {data:[]};
 const {data:responses}=visible.length?await apnaSupabase.from("seller_review_responses").select("review_id,seller_id,body").in("review_id",visible.map(r=>r.id)): {data:[]};
 const {data:voteRows}=session?await apnaSupabase.from("review_helpful_votes").select("review_id").eq("user_id",session.user.id):{data:[]};
 const voted=new Set((voteRows||[]).map(x=>x.review_id));
 const voteCounts={};(visible.length?await apnaSupabase.from("review_helpful_votes").select("review_id").in("review_id",visible.map(r=>r.id)):{data:[]}).data?.forEach(x=>voteCounts[x.review_id]=(voteCounts[x.review_id]||0)+1);
 const imageUrl=p=>apnaSupabase.storage.from("review-images").getPublicUrl(p).data.publicUrl;
 box.innerHTML='<div class="reviews-head"><div><p class="eyebrow">CUSTOMER REVIEWS</p><h2>Reviews & ratings</h2></div><div class="review-average"><strong>'+(visible.length?avg.toFixed(1):"—")+'</strong><span>'+stars(Math.round(avg))+'</span><small>'+visible.length+' published review'+(visible.length===1?"":"s")+'</small></div></div>'+
 (eligible.length?'<form id="reviewForm" class="review-form"><label>Order<select id="reviewOrder" required>'+eligible.map(o=>'<option value="'+reviewEsc(o.id)+'">'+reviewEsc(o.order_number)+'</option>').join("")+'</select></label><label>Rating<select id="reviewRating" required><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Title<input id="reviewTitle" maxlength="120" placeholder="What did you think?"></label><label>Review<textarea id="reviewBody" maxlength="2000" rows="4" placeholder="Share your experience"></textarea></label><label class="review-upload">Product images (optional)<input id="reviewImages" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><button class="primary-btn" type="submit">Submit review →</button><p id="reviewMessage" class="review-message"></p></form>':session?'<p class="checkout-note">You can review this product after a delivered order.</p>':'<p class="checkout-note">Sign in after delivery to leave a verified review.</p>')+
 (ownPending.length?'<p class="review-pending">Your '+ownPending.length+' review submission'+(ownPending.length===1?" is":"s are")+' awaiting moderation.</p>':"")+
 (visible.length?'<div class="review-list">'+visible.map(r=>{const imgs=(images||[]).filter(i=>i.review_id===r.id);const resp=(responses||[]).find(x=>x.review_id===r.id);return '<article class="review-card" data-review="'+reviewEsc(r.id)+'"><div class="review-card-top"><div><strong class="review-stars">'+reviewEsc(stars(r.rating))+'</strong>'+(r.verified_purchase?'<span class="verified-review">Verified purchase</span>':"")+'</div><small>'+reviewEsc(new Date(r.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}))+'</small></div>'+(r.title?'<h3>'+reviewEsc(r.title)+'</h3>':"")+(r.body?'<p>'+reviewEsc(r.body)+'</p>':"")+(imgs.length?'<div class="review-images">'+imgs.map(i=>'<img src="'+reviewEsc(imageUrl(i.storage_path))+'" alt="Customer review image" loading="lazy">').join("")+'</div>':"")+(resp?'<div class="review-response"><strong>Seller response</strong><p>'+reviewEsc(resp.body)+'</p></div>':"")+'<div class="review-actions"><button type="button" data-help="'+reviewEsc(r.id)+'">'+(voted.has(r.id)?"✓ Helpful":"Helpful")+' ('+(voteCounts[r.id]||0)+')</button><button type="button" data-report-toggle="'+reviewEsc(r.id)+'">Report</button></div><form class="review-report" data-report="'+reviewEsc(r.id)+'"><select name="reason" required><option value="">Report reason</option><option value="spam">Spam</option><option value="abuse">Abuse</option><option value="offensive">Offensive</option><option value="fake_review">Potentially fake</option><option value="irrelevant">Irrelevant</option><option value="other">Other</option></select><textarea name="details" maxlength="1000" placeholder="Optional details"></textarea><button class="review-actions" type="submit">Submit report</button><span class="review-message"></span></form></article>'}).join("")+'</div>':'<div class="reviews-empty">No published reviews yet. Verified customers can share their experience after delivery.</div>');
 const form=document.getElementById("reviewForm");
 if(form)form.onsubmit=async e=>{e.preventDefault();const msg=document.getElementById("reviewMessage"),btn=form.querySelector("button[type=submit]");btn.disabled=true;msg.textContent="Submitting…";const {data,error}=await apnaSupabase.rpc("create_review_secure",{p_product_id:reviewProductId,p_order_id:document.getElementById("reviewOrder").value,p_rating:Number(document.getElementById("reviewRating").value),p_title:document.getElementById("reviewTitle").value,p_body:document.getElementById("reviewBody").value});if(error){msg.textContent=error.message||"Could not submit review.";btn.disabled=false;return}const files=[...(document.getElementById("reviewImages")?.files||[])].slice(0,5);for(const file of files){const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=session.user.id+"/"+data.id+"-"+crypto.randomUUID()+"."+ext;const up=await apnaSupabase.storage.from("review-images").upload(path,file,{contentType:file.type,upsert:false});if(!up.error)await apnaSupabase.from("review_images").insert({review_id:data.id,user_id:session.user.id,storage_path:path})}await renderReviews()};
 box.querySelectorAll("[data-help]").forEach(b=>b.onclick=async()=>{const id=b.dataset.help;const action=voted.has(id)?"remove":"add";const r=await apnaSupabase.rpc(action==="add"?"review_add_helpful_vote":"review_remove_helpful_vote",{p_review_id:id});if(r.error){alert(r.error.message||"Could not update helpful vote.");return}await renderReviews()});
 box.querySelectorAll("[data-report-toggle]").forEach(b=>b.onclick=()=>{const f=box.querySelector('[data-report="'+b.dataset.reportToggle+'"]');if(f)f.style.display=f.style.display==="block"?"none":"block"});
 box.querySelectorAll("[data-report]").forEach(f=>f.onsubmit=async e=>{e.preventDefault();const msg=f.querySelector(".review-message"),r=await apnaSupabase.from("review_reports").insert({review_id:f.dataset.report,reporter_id:session?.user?.id,reason:f.reason.value,details:f.details.value.trim()||null});if(r.error){msg.textContent=r.error.message||"Could not submit report.";return}msg.textContent="Report submitted for moderation.";f.reset()});
}
const reviewWait=setInterval(()=>{if(document.getElementById("product")?.querySelector(".product-details")){clearInterval(reviewWait);renderReviews()}},100);