const reviewProductId=new URLSearchParams(location.search).get("id");
function reviewEsc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function stars(n){n=Math.max(0,Math.min(5,Number(n)||0));return "★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
async function renderReviews(){
 const product=document.getElementById("product");if(!product||!reviewProductId)return;
 const box=document.createElement("section");box.className="product-reviews";box.id="reviews";product.appendChild(box);
 const {data:rows,error}=await apnaSupabase.from("reviews").select("id,rating,title,body,created_at,verified_purchase,user_id,order_id").eq("product_id",reviewProductId).order("created_at",{ascending:false});
 if(error){box.innerHTML='<div class="reviews-empty">Reviews are temporarily unavailable.</div>';return}
 const reviews=rows||[],avg=reviews.length?reviews.reduce((s,r)=>s+Number(r.rating||0),0)/reviews.length:0;
 const {data:{session}}=await apnaSupabase.auth.getSession();let eligible=[];
 if(session){const q=await apnaSupabase.from("orders").select("id,order_number,order_items!inner(product_id)").eq("user_id",session.user.id).eq("delivery_status","delivered").eq("order_items.product_id",reviewProductId).order("created_at",{ascending:false});const used=new Set(reviews.filter(r=>r.user_id===session.user.id).map(r=>r.order_id));eligible=(q.data||[]).filter(o=>!used.has(o.id))}
 box.innerHTML='<div class="reviews-head"><div><p class="eyebrow">CUSTOMER REVIEWS</p><h2>Reviews & ratings</h2></div><div class="review-average"><strong>'+(reviews.length?avg.toFixed(1):"—")+'</strong><span>'+stars(Math.round(avg))+'</span><small>'+reviews.length+' review'+(reviews.length===1?"":"s")+'</small></div></div>'+
 (eligible.length?'<form id="reviewForm" class="review-form"><label>Order<select id="reviewOrder" required>'+eligible.map(o=>'<option value="'+reviewEsc(o.id)+'">'+reviewEsc(o.order_number)+'</option>').join("")+'</select></label><label>Rating<select id="reviewRating" required><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Title<input id="reviewTitle" maxlength="120" placeholder="What did you think?"></label><label>Review<textarea id="reviewBody" maxlength="2000" rows="4" placeholder="Share your experience"></textarea></label><button class="primary-btn" type="submit">Submit review →</button><p id="reviewMessage" class="checkout-note"></p></form>':session?'<p class="checkout-note">You can review this product after a delivered order.</p>':'<p class="checkout-note">Sign in after delivery to leave a verified review.</p>')+
 (reviews.length?'<div class="review-list">'+reviews.map(r=>'<article class="review-card"><div class="review-card-top"><div><strong>'+reviewEsc(stars(r.rating))+'</strong>'+(r.verified_purchase?'<span class="verified-review">Verified purchase</span>':"")+'</div><small>'+reviewEsc(new Date(r.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}))+'</small></div>'+(r.title?'<h3>'+reviewEsc(r.title)+'</h3>':"")+(r.body?'<p>'+reviewEsc(r.body)+'</p>':"")+'</article>').join("")+'</div>':'<div class="reviews-empty">No reviews yet. Be the first verified customer to share your experience.</div>');
 const form=document.getElementById("reviewForm");if(form)form.onsubmit=async e=>{e.preventDefault();const msg=document.getElementById("reviewMessage"),btn=form.querySelector("button");btn.disabled=true;msg.textContent="Submitting…";const {error}=await apnaSupabase.rpc("create_review_secure",{p_product_id:reviewProductId,p_order_id:document.getElementById("reviewOrder").value,p_rating:Number(document.getElementById("reviewRating").value),p_title:document.getElementById("reviewTitle").value,p_body:document.getElementById("reviewBody").value});if(error){msg.textContent=error.message||"Could not submit review.";btn.disabled=false;return}await renderReviews()};
}
const reviewWait=setInterval(()=>{if(document.getElementById("product")?.querySelector(".product-details")){clearInterval(reviewWait);renderReviews()}},100);