const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const COURIER_API="https://xxedwtmdylfufrfzyrdb.supabase.co/functions/v1/";
const STATUSES=["New","Accepted","Packing","Ready for Pickup","Pickup Scheduled","Picked Up","Shipped","In Transit","Out for Delivery","Delivered","Cancelled","Return","Exchange","RTO"];
let rows=[];
async function callCourier(fn,body){const{data:{session}}=await apnaSupabase.auth.getSession();if(!session)throw new Error("Sign in required.");const r=await fetch(COURIER_API+fn,{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Courier request failed.");return d;}
function filtered(){const q=$("search").value.trim().toLowerCase(),s=$("status").value,d=$("delivery").value;return rows.filter(o=>(!s||(o.seller_order_status||"New")===s)&&(!d||o.delivery_status===d)&&(!q||(o.order_number+" "+o.items.map(i=>i.product_name+" "+(i.sku||"")).join(" ")).toLowerCase().includes(q)));}
function render(){const list=filtered();$("message").textContent=list.length+" order(s)";if(!list.length){$("panel").innerHTML='<div class="empty">No matching orders.</div>';return}$("panel").innerHTML='<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Products / Variants</th><th>Qty</th><th>Seller Total</th><th>Payment</th><th>Status</th><th>Courier / AWB</th><th>Action</th></tr></thead><tbody>'+list.map(o=>{const a=o.shipping_address||{},customer=a.name||a.full_name||"Customer";const items=o.items||[];return '<tr><td><strong>'+esc(o.order_number)+'</strong><br><span class="muted">'+new Date(o.created_at).toLocaleString("en-IN")+'</span></td><td>'+esc(customer)+'<br><span class="muted">'+esc([a.city,a.state,a.pincode].filter(Boolean).join(", "))+'</span></td><td>'+items.map(i=>esc(i.product_name)+'<br><span class="muted">'+esc([i.size,i.color,i.sku].filter(Boolean).join(" · ")||"Standard")+'</span>').join("<hr>")+'</td><td>'+items.reduce((n,i)=>n+Number(i.quantity||0),0)+'</td><td>'+money(o.seller_total)+'</td><td>'+esc(o.payment_method==="cod"?"COD":o.payment_status||"Online")+'<br><span class="muted">'+esc(o.payment_provider||"")+'</span></td><td><span class="status">'+esc(o.seller_order_status||"New")+'</span><br><span class="muted">'+esc(o.delivery_status||"")+'</span></td><td>'+esc(o.tracking_provider||"Not assigned")+'<br>'+esc(o.tracking_number||"AWB pending")+'</td><td><button class="btn" data-view="'+o.id+'">Details</button></td></tr>'}).join("")+'</tbody></table>';document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showDetail(b.dataset.view));}
function showDetail(id){const o=rows.find(x=>x.id===id);if(!o)return;const a=o.shipping_address||{};$("detail").innerHTML='<div class="detail"><div class="top"><div><h2>'+esc(o.order_number)+'</h2><span class="status">'+esc(o.seller_order_status||"New")+'</span></div><div class="actions"><select id="newStatus">'+STATUSES.map(s=>'<option>'+esc(s)+'</option>').join("")+'</select><input id="statusNote" maxlength="250" placeholder="Status note (optional)"><button class="btn" id="saveStatus">Save status</button></div></div><div class="detail-grid"><div class="detail-card"><span>Customer</span><strong>'+esc(a.name||a.full_name||"Customer")+' · '+esc(a.phone||"Phone unavailable")+'</strong><br>'+esc([a.address,a.city,a.state,a.pincode].filter(Boolean).join(", "))+'</div><div class="detail-card"><span>Payment</span><strong>'+esc(o.payment_method==="cod"?"COD":o.payment_status||"Online")+'</strong><br>'+esc(o.payment_provider||"")+(o.payment_reference?" · Ref "+esc(o.payment_reference):"")+'</div><div class="detail-card"><span>Courier / Tracking</span><strong>'+esc(o.tracking_provider||"Not assigned")+'</strong><br>AWB / Tracking: '+esc(o.tracking_number||"Not assigned")+'<br>Delivery: '+esc(o.delivery_status||"")+'</div></div><div class="items"><strong>Products, variants, quantity & price</strong>'+((o.items||[]).map(i=>'<div>'+esc(i.product_name)+' · '+esc([i.size,i.color,i.sku].filter(Boolean).join(" / ")||"Standard")+' · Qty '+Number(i.quantity)+' · '+money(i.unit_price)+'</div>').join("")||"<div>No items.</div>")+'</div><div class="actions"><button class="btn" id="closeDetail">Close</button><button class="btn" id="courierBtn">Create / Assign Courier</button><button class="btn" id="pickupBtn" hidden>Schedule Pickup</button><button class="btn" id="labelBtn" hidden>Generate Label</button><button class="btn" id="manifestBtn" hidden>Generate Manifest</button><button class="btn" id="trackBtn" hidden>Sync Tracking</button></div><div class="timeline"><strong>Status history</strong><div id="history">Loading…</div></div></div>';$("newStatus").value=o.seller_order_status||"New";$("closeDetail").onclick=()=>{$("detail").innerHTML=""};$("saveStatus").onclick=()=>saveStatus(o.id);$("courierBtn").onclick=()=>courierAction(o.id); const shipment=getShipment(o); if(shipment){$("pickupBtn").hidden=false;$("labelBtn").hidden=false;$("manifestBtn").hidden=false;$("trackBtn").hidden=false;$("pickupBtn").onclick=()=>shipmentAction(shipment.id,"pickup");$("labelBtn").onclick=()=>shipmentAction(shipment.id,"label");$("manifestBtn").onclick=()=>shipmentAction(shipment.id,"manifest");$("trackBtn").onclick=()=>shipmentAction(shipment.id,"track");} loadHistory(o.id);}
async function saveStatus(id){const status=$("newStatus").value,note=$("statusNote").value.trim()||null;const{error}=await apnaSupabase.rpc("seller_set_order_status",{p_order_id:id,p_status:status,p_note:note});if(error){alert(error.message);return}await load();showDetail(id);}
async function loadHistory(id){const{data,error}=await apnaSupabase.from("seller_order_status_events").select("status,note,created_at").eq("order_id",id).order("created_at",{ascending:false}).limit(50);$("history").innerHTML=error?'<span class="error">'+esc(error.message)+'</span>':(!data?.length?'<span class="muted">No status events recorded yet.</span>':data.map(x=>'<div class="timeline-item"><strong>'+esc(x.status)+'</strong> · '+new Date(x.created_at).toLocaleString("en-IN")+(x.note?'<br><span class="muted">'+esc(x.note)+'</span>':'')+'</div>').join(""))}
async function courierAction(orderId){const o=rows.find(x=>x.id===orderId);if(!o)return;try{const pickupName=prompt("Shiprocket pickup location name (must already exist in your Shiprocket account):","");if(pickupName===null)return;const pickupAddress=prompt("Seller pickup full address:","");if(pickupAddress===null)return;const pickupCity=prompt("Pickup city:","");if(pickupCity===null)return;const pickupState=prompt("Pickup state:","");if(pickupState===null)return;const pickupPincode=prompt("Pickup pincode:","");if(pickupPincode===null)return;const pickupPhone=prompt("Pickup phone:","");if(pickupPhone===null)return;const weight=Number(prompt("Package weight in kg (minimum 0.50):","0.50"));if(!(weight>=0.5))throw new Error("Minimum package weight is 0.50 kg.");const length=Number(prompt("Package length in cm:","20")),width=Number(prompt("Package width in cm:","15")),height=Number(prompt("Package height in cm:","10"));if(!(length>0&&width>0&&height>0))throw new Error("Valid package dimensions are required.");const shipAddress=o.shipping_address||{};const service=await callCourier("apna-courier-v3",{action:"serviceability",pickup_postcode:pickupPincode,delivery_postcode:shipAddress.pincode,weight_kg:weight,cod:o.payment_method==="cod"||o.payment_status==="cod"});const cs=service.couriers||[];if(!cs.length)throw new Error("No courier partner is currently serviceable for this route.");const list=cs.map((c,i)=>(i+1)+". "+(c.name||"Courier")+" | ₹"+Number(c.freight_charge||c.rate||0).toLocaleString("en-IN")+" | ETA "+(c.etd||c.etd_hours||"N/A")).join("
");const pick=prompt("Available courier partners:

"+list+"

Enter the courier number to use:","1");const idx=Number(pick)-1;if(!Number.isInteger(idx)||!cs[idx])return;const chosen=cs[idx];if(!confirm("Create the real Shiprocket shipment with "+(chosen.name||"selected courier")+"?

This will create a provider order/shipment."))return;const created=await callCourier("apna-courier-create",{order_id:orderId,weight_kg:weight,length_cm:length,width_cm:width,height_cm:height,pickup:{name:pickupName,address:pickupAddress,city:pickupCity,state:pickupState,pincode:pickupPincode,phone:pickupPhone}});const shipment=created.shipment;if(!shipment?.id)throw new Error("Shipment was not saved locally.");const awb=await callCourier("apna-courier-v3",{action:"assign_awb",shipment_id:shipment.id,courier_id:Number(chosen.id)});alert("Shipment created. Courier: "+(awb.courier_name||chosen.name||"Selected courier")+"
AWB: "+(awb.shipment?.awb_number||"Assigned"));await load();showDetail(orderId);}catch(e){alert(e.message||"Courier operation failed.");}}
async function load(){const{data:s,error:ae}=await apnaSupabase.auth.getSession();if(ae||!s.session){location.href="auth.html";return}const{data,error}=await apnaSupabase.rpc("get_seller_orders",{p_status:null,p_delivery_status:$("delivery").value||null});if(error){$("message").textContent=error.message;return}rows=Array.isArray(data)?data:[];const ids=rows.map(x=>x.id).filter(Boolean);if(ids.length){const sr=await apnaSupabase.from("shipments").select("id,order_id,direction,provider,awb_number,pickup_id,status,label_url,manifest_url,tracking_url").in("order_id",ids);if(!sr.error){const map=new Map((sr.data||[]).map(s=>[s.order_id,s]));rows=rows.map(x=>({...x,shipments:map.has(x.id)?[map.get(x.id)]:[]}));}}render();}
$("reload").onclick=load;$("clear").onclick=()=>{$("search").value="";$("status").value="";$("delivery").value="";render()};$("search").oninput=render;$("status").onchange=render;$("delivery").onchange=load;load();
function getShipment(o){return o.shipments?.find(s=>s.direction==="outbound")||null;}
async function shipmentAction(id,action){try{const d=await callCourier("apna-courier-v3",{action,shipment_id:id});alert(action==="track"?"Tracking sync requested.":"Courier action completed.");await load();showDetail(d.shipment?.order_id||rows.find(x=>getShipment(x)?.id===id)?.id);}catch(e){alert(e.message||"Courier action failed.");}}
