const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);const editId=params.get("id");let user,role;function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">": "&gt;",'"':"&quot;","'":"&#39;"}[c]));}

async function loadImages(){
 if(!editId)return;
 const {data,error}=await apnaSupabase.from("product_images").select("id,storage_path,is_primary").eq("product_id",editId).order("is_primary",{ascending:false}).order("sort_order");
 if(error)return;
 $("imageList").innerHTML=(data||[]).map(i=>{const u=apnaSupabase.storage.from("product-images").getPublicUrl(i.storage_path).data.publicUrl;return '<div class="image-item"><img src="'+esc(u)+'"><label><input type="radio" name="primaryImage" '+(i.is_primary?"checked":"")+' data-primary="'+i.id+'"> Main</label><button type="button" class="btn remove" data-remove="'+i.id+'">Remove</button></div>'}).join("");
 $("imageList").querySelectorAll("[data-primary]").forEach(x=>x.onchange=async()=>{await apnaSupabase.from("product_images").update({is_primary:false}).eq("product_id",editId);await apnaSupabase.from("product_images").update({is_primary:true}).eq("id",x.dataset.primary);});
 $("imageList").querySelectorAll("[data-remove]").forEach(x=>x.onclick=async()=>{const row=data.find(i=>i.id===x.dataset.remove);if(row)await apnaSupabase.storage.from("product-images").remove([row.storage_path]);await apnaSupabase.from("product_images").delete().eq("id",x.dataset.remove);loadImages();});
}

function addVariant(v={}){const row=document.createElement("div");row.className="variant";row.innerHTML='<input class="vsize" placeholder="Size" value="'+esc(v.size)+'"><input class="vcolor" placeholder="Color" value="'+esc(v.color)+'"><input class="vsku" placeholder="SKU" value="'+esc(v.sku)+'"><input class="vstock" type="number" min="0" placeholder="Stock" value="'+(v.stock??0)+'"><button type="button" class="btn remove">Remove</button>';row.querySelector(".remove").onclick=()=>row.remove();$("variantRows").appendChild(row);}
async function boot(){const {data:s}=await apnaSupabase.auth.getSession();if(!s.session){location.href="auth.html";return;}user=s.session.user;const {data:p}=await apnaSupabase.from("profiles").select("role").eq("id",user.id).single();if(!p||!["seller","admin"].includes(p.role)){location.href="account.html";return;}role=p.role;const {data:cats}=await apnaSupabase.from("categories").select("id,name").order("name");$("category").innerHTML=(cats||[]).map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join("");if(editId){$("heading").textContent="Edit product";const {data:prod,error}=await apnaSupabase.from("products").select("id,name,description,price,compare_at_price,status,category_id,seller_id").eq("id",editId).single();if(error||!prod|| (role==="seller"&&prod.seller_id!==user.id)){location.href="seller-products.html";return;}$("name").value=prod.name||"";$("description").value=prod.description||"";$("price").value=prod.price??"";$("compare").value=prod.compare_at_price??"";$("status").value=prod.status||"draft";$("category").value=prod.category_id||"";const {data:vs}=await apnaSupabase.from("product_variants").select("size,color,sku,stock").eq("product_id",editId).order("created_at");(vs||[]).forEach(addVariant);}$("addVariant").onclick=()=>addVariant();if(!editId)addVariant();await loadImages();$("images").onchange=async()=>{if(!editId){$("msg").textContent="Save the product first, then upload images.";return;}for(const file of [...$("images").files]){if(file.size>5242880){$("msg").textContent="Each image must be 5 MB or smaller.";continue;}const ext=file.name.split(".").pop().toLowerCase();const path=user.id+"/"+editId+"/"+crypto.randomUUID()+"."+ext;const up=await apnaSupabase.storage.from("product-images").upload(path,file,{contentType:file.type});if(up.error){$("msg").textContent=up.error.message;continue;}const {data:imgs}=await apnaSupabase.from("product_images").select("id").eq("product_id",editId);const ins=await apnaSupabase.from("product_images").insert({product_id:editId,storage_path:path,alt_text:$("name").value.trim(),sort_order:(imgs||[]).length,is_primary:(imgs||[]).length===0});if(ins.error)await apnaSupabase.storage.from("product-images").remove([path]);}$("images").value="";loadImages();};}
$("form").addEventListener("submit",async e=>{e.preventDefault();$("save").disabled=true;$("msg").textContent="Saving…";try{const name=$("name").value.trim();const slug=(name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Date.now().toString(36)).slice(0,180);const payload={name,slug,description:$("description").value.trim(),price:Number($("price").value),compare_at_price:$("compare").value?Number($("compare").value):null,status:$("status").value,category_id:$("category").value||null};let productId=editId;if(editId){const {data:existing}=await apnaSupabase.from("products").select("seller_id").eq("id",editId).single();if(role==="seller"&&existing?.seller_id!==user.id)throw new Error("You can only edit your own products.");delete payload.slug;const {error}=await apnaSupabase.from("products").update(payload).eq("id",editId);if(error)throw error;await apnaSupabase.from("product_variants").delete().eq("product_id",editId);}else{payload.seller_id=user.id;const {data,error}=await apnaSupabase.from("products").insert(payload).select("id").single();if(error)throw error;productId=data.id;}
const rows=[...document.querySelectorAll(".variant")].map(r=>({product_id:productId,size:r.querySelector(".vsize").value.trim()||null,color:r.querySelector(".vcolor").value.trim()||null,sku:r.querySelector(".vsku").value.trim()||null,stock:Math.max(0,Number(r.querySelector(".vstock").value)||0)}));if(rows.length){const {error}=await apnaSupabase.from("product_variants").insert(rows);if(error)throw error;}location.href="seller-products.html";}catch(err){$("msg").className="msg error";$("msg").textContent=err.message||"Could not save product.";$("save").disabled=false;}});boot();