import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function auth(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))throw new Error("Authentication required");const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!,{global:{headers:{Authorization:h}}});const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error("Authentication required");const {data:p}=await sb.from("profiles").select("role").eq("id",user.id).maybeSingle();if(!p||!["seller","admin"].includes(p.role))throw new Error("Seller or admin access required");return {sb,user,role:p.role}}
async function token(){const email=Deno.env.get("SHIPROCKET_API_EMAIL"),password=Deno.env.get("SHIPROCKET_API_PASSWORD");if(!email||!password)throw new Error("Shiprocket API credentials are not configured.");const r=await fetch("https://apiv2.shiprocket.in/v1/external/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.token)throw new Error("Shiprocket authentication failed.");return d.token as string}
async function api(path:string,t:string,method="POST",body?:unknown){const r=await fetch("https://apiv2.shiprocket.in/v1/external/"+path,{method,headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error("Shiprocket request failed ("+r.status+").");return d}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const {sb,user,role}=await auth(req),b=await req.json(),action=String(b?.action||""),t=await token();if(action==="serviceability"){const pp=String(b.pickup_postcode||""),dp=String(b.delivery_postcode||""),w=Number(b.weight_kg||0);if(!/^\d{6}$/.test(pp)||!/^\d{6}$/.test(dp)||!(w>0))return json({error:"Valid pincodes and weight are required."},400);const u=new URL("https://apiv2.shiprocket.in/v1/external/courier/serviceability/");u.searchParams.set("pickup_postcode",pp);u.searchParams.set("delivery_postcode",dp);u.searchParams.set("weight",String(w));u.searchParams.set("cod",b.cod?"1":"0");if(b.length_cm)u.searchParams.set("length",String(b.length_cm));if(b.width_cm)u.searchParams.set("breadth",String(b.width_cm));if(b.height_cm)u.searchParams.set("height",String(b.height_cm));if(b.declared_value)u.searchParams.set("declared_value",String(b.declared_value));const r=await fetch(u,{headers:{Authorization:"Bearer "+t}}),d=await r.json().catch(()=>null);if(!r.ok)return json({error:"Courier serviceability request failed.",provider_status:r.status},502);return json({provider:"shiprocket",couriers:(d?.data?.available_courier_companies||[]).map((c:any)=>({id:c.courier_company_id??null,name:c.courier_name??null,freight_charge:c.freight_charge??null,rate:c.rate??null,etd:c.etd??null,etd_hours:c.etd_hours??null,rating:c.rating??null}))})}
if(action==="api_status"){return json({provider:"shiprocket",status:"authenticated",checked_at:new Date().toISOString()});}
if(action==="pickup_locations"){const d=await api("settings/company/pickup",t,"GET");const list=d?.data?.shipping_address||[];return json({provider:"shiprocket",pickup_locations:list.map((x:any)=>({id:x.id??null,pickup_location:x.pickup_location??null,name:x.name??null,address:x.address??null,address_2:x.address_2??null,city:x.city??null,state:x.state??null,pin_code:x.pin_code??null,phone:x.phone??null,status:x.status??null,is_primary_location:x.is_primary_location??null}))});}
if(action==="courier_list"){const d=await api("courier/courierListWithCounts",t,"GET");return json({provider:"shiprocket",couriers:d?.data??d});}
const shipmentId=String(b.shipment_id||"");if(!shipmentId)return json({error:"shipment_id is required."},400);const {data:sh}=await sb.from("shipments").select("*").eq("id",shipmentId).maybeSingle();if(!sh)return json({error:"Shipment not found."},404);if(role==="seller"&&sh.seller_id!==user.id)return json({error:"Shipment access denied."},403);
if(action==="assign_awb"){const courierId=Number(b.courier_id||0);if(!(courierId>0))return json({error:"courier_id is required."},400);const d=await api("courier/assign/awb",t,"POST",{shipment_id:Number(sh.provider_shipment_id),courier_id:courierId});const awb=d?.response?.data?.awb_code??d?.awb_code??d?.data?.awb_code??null;const courier=d?.response?.data?.courier_name??d?.courier_name??d?.data?.courier_name??null;const up={awb_number:awb?String(awb):sh.awb_number,status:awb?"manifested":sh.status,tracking_url:awb?"https://shiprocket.co/tracking/"+encodeURIComponent(String(awb)):sh.tracking_url,raw_provider_reference:d};const {data:n,error}=await sb.from("shipments").update(up).eq("id",sh.id).select().single();if(error)return json({error:"AWB assigned by provider but local update failed.",provider_response:d},502);return json({shipment:n,courier_name:courier,provider_response:d})}
if(action==="pickup"){const d=await api("courier/generate/pickup",t,"POST",{shipment_id:[Number(sh.provider_shipment_id)]});const pickup=d?.response?.data?.pickup_scheduled_date??d?.pickup_scheduled_date??null;const pickupId=d?.response?.data?.pickup_id??d?.pickup_id??d?.data?.pickup_id??null;const {data:n,error}=await sb.from("shipments").update({status:"pickup_scheduled",pickup_id:pickupId?String(pickupId):sh.pickup_id,raw_provider_reference:d}).eq("id",sh.id).select().single();if(error)return json({error:"Pickup requested but local update failed.",provider_response:d},502);return json({shipment:n,pickup_scheduled_date:pickup,provider_response:d})}
if(action==="label"){const d=await api("courier/generate/label",t,"POST",{shipment_id:[Number(sh.provider_shipment_id)]});const url=d?.label_url??d?.response?.data?.label_url??d?.data?.label_url??null;const {data:n,error}=await sb.from("shipments").update({label_url:url?String(url):sh.label_url,raw_provider_reference:d}).eq("id",sh.id).select().single();if(error)return json({error:"Label generated but local update failed.",provider_response:d},502);return json({shipment:n,provider_response:d})}
if(action==="manifest"){const d=await api("manifests/generate",t,"POST",{shipment_id:[Number(sh.provider_shipment_id)]});const url=d?.manifest_url??d?.response?.data?.manifest_url??d?.data?.manifest_url??null;const {data:n,error}=await sb.from("shipments").update({manifest_url:url?String(url):sh.manifest_url,raw_provider_reference:d}).eq("id",sh.id).select().single();if(error)return json({error:"Manifest generated but local update failed.",provider_response:d},502);return json({shipment:n,provider_response:d})}
if(action==="track"){if(!sh.awb_number)return json({error:"Shipment has no AWB yet."},409);const d=await api("courier/track/awb/"+encodeURIComponent(sh.awb_number),t,"GET");return json({shipment:sh,tracking:d})}
return json({error:"Unsupported action."},400)}catch(e){console.error("apna-courier-v3",e);return json({error:e instanceof Error?e.message:"Courier operation failed."},500)}});