-- Phase 70: audit trail and admin observability.
create table if not exists public.audit_logs (
 id bigint generated by default as identity primary key,
 actor_id uuid references public.profiles(id) on delete set null,
 action text not null check (action ~ '^[a-z][a-z0-9_.-]{1,79}$'),
 entity_type text not null check (entity_type ~ '^[a-z][a-z0-9_.-]{1,79}$'),
 entity_id text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon, authenticated;
create or replace function public.record_audit_event(p_action text,p_entity_type text,p_entity_id text default null,p_metadata jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint; begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 insert into public.audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),lower(trim(p_action)),lower(trim(p_entity_type)),nullif(trim(p_entity_id),''),coalesce(p_metadata,'{}'::jsonb)) returning id into v_id; return v_id;
end $$;
create or replace function public.admin_list_audit_logs(p_limit integer default 100)
returns table(id bigint,actor_id uuid,actor_name text,action text,entity_type text,entity_id text,metadata jsonb,created_at timestamptz)
language sql stable security definer set search_path=public,pg_temp as $$
 select a.id,a.actor_id,p.full_name,a.action,a.entity_type,a.entity_id,a.metadata,a.created_at from public.audit_logs a left join public.profiles p on p.id=a.actor_id
 where exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='admin') order by a.created_at desc limit least(greatest(coalesce(p_limit,100),1),500);
$$;
create or replace function public.admin_observability_summary()
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object('generated_at',now(),'audit_events_24h',(select count(*) from public.audit_logs where created_at>=now()-interval '24 hours'),'analytics_events_24h',(select count(*) from public.analytics_events where created_at>=now()-interval '24 hours'),'shipments_total',(select count(*) from public.shipments),'failed_shipments',(select count(*) from public.shipments where status in ('failed','rto','cancelled','exception')),'open_returns',(select count(*) from public.return_requests where status in ('requested','approved','pickup_scheduled','picked_up','in_transit'))) where exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='admin');
$$;
revoke execute on function public.record_audit_event(text,text,text,jsonb) from public,anon,authenticated;
revoke execute on function public.admin_list_audit_logs(integer) from public,anon,authenticated;
revoke execute on function public.admin_observability_summary() from public,anon,authenticated;
grant execute on function public.record_audit_event(text,text,text,jsonb) to authenticated;
grant execute on function public.admin_list_audit_logs(integer) to authenticated;
grant execute on function public.admin_observability_summary() to authenticated;
-- Audit feature-flag administration without exposing audit rows to clients.
create or replace function public.admin_save_feature_flag(
 p_flag_id uuid,p_flag_key text,p_description text,p_enabled boolean,p_environment text,p_rollout_percent numeric,p_client_visible boolean
) returns public.feature_flags language plpgsql security definer set search_path=public,pg_temp as $$
declare v_row public.feature_flags;
begin
 if not public.is_admin_user() then raise exception 'Admin access required'; end if;
 if p_flag_key is null or p_flag_key !~ '^[a-z][a-z0-9_.-]{1,79}$' then raise exception 'Invalid flag key'; end if;
 if p_environment not in ('production','staging','development') then raise exception 'Invalid environment'; end if;
 if p_rollout_percent < 0 or p_rollout_percent > 100 then raise exception 'Invalid rollout percentage'; end if;
 if p_flag_id is null then
  insert into public.feature_flags(flag_key,description,enabled,environment,rollout_percent,client_visible,created_by)
  values(lower(trim(p_flag_key)),nullif(trim(p_description),''),coalesce(p_enabled,false),p_environment,p_rollout_percent,coalesce(p_client_visible,false),auth.uid()) returning * into v_row;
  perform public.record_audit_event('feature_flag.created','feature_flag',v_row.id::text,jsonb_build_object('flag_key',v_row.flag_key,'enabled',v_row.enabled,'environment',v_row.environment,'rollout_percent',v_row.rollout_percent));
 else
  update public.feature_flags set flag_key=lower(trim(p_flag_key)),description=nullif(trim(p_description),''),enabled=coalesce(p_enabled,false),environment=p_environment,rollout_percent=p_rollout_percent,client_visible=coalesce(p_client_visible,false),updated_at=now() where id=p_flag_id returning * into v_row;
  if v_row.id is null then raise exception 'Feature flag not found'; end if;
  perform public.record_audit_event('feature_flag.updated','feature_flag',v_row.id::text,jsonb_build_object('flag_key',v_row.flag_key,'enabled',v_row.enabled,'environment',v_row.environment,'rollout_percent',v_row.rollout_percent));
 end if;
 return v_row;
end $$;
create or replace function public.admin_delete_feature_flag(p_flag_id uuid)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$
declare v_key text;
begin
 if not public.is_admin_user() then raise exception 'Admin access required'; end if;
 select flag_key into v_key from public.feature_flags where id=p_flag_id;
 delete from public.feature_flags where id=p_flag_id;
 if found then perform public.record_audit_event('feature_flag.deleted','feature_flag',p_flag_id::text,jsonb_build_object('flag_key',v_key)); end if;
 return found;
end $$;
