alter table public.product_images add column if not exists variant_id uuid references public.product_variants(id) on delete cascade;
create index if not exists product_images_variant_id_idx on public.product_images(variant_id);
alter table public.product_images enable row level security;
drop policy if exists product_images_public_read on public.product_images;
drop policy if exists product_images_authenticated_read on public.product_images;
drop policy if exists product_images_seller_insert on public.product_images;
drop policy if exists product_images_seller_update on public.product_images;
drop policy if exists product_images_seller_delete on public.product_images;
drop policy if exists product_images_public_select on public.product_images;
create policy product_images_public_read on public.product_images for select to anon using (exists (select 1 from public.products p where p.id=product_images.product_id and p.status='active'));
create policy product_images_authenticated_read on public.product_images for select to authenticated using (exists (select 1 from public.products p where p.id=product_images.product_id and (p.status='active' or private.is_admin() or (private.is_seller() and p.seller_id=(select auth.uid())))));
create policy product_images_seller_insert on public.product_images for insert to authenticated with check (private.is_admin() or (private.is_seller() and exists (select 1 from public.products p where p.id=product_images.product_id and p.seller_id=(select auth.uid()))));
create policy product_images_seller_update on public.product_images for update to authenticated using (private.is_admin() or (private.is_seller() and exists (select 1 from public.products p where p.id=product_images.product_id and p.seller_id=(select auth.uid())))) with check (private.is_admin() or (private.is_seller() and exists (select 1 from public.products p where p.id=product_images.product_id and p.seller_id=(select auth.uid()))));
create policy product_images_seller_delete on public.product_images for delete to authenticated using (private.is_admin() or (private.is_seller() and exists (select 1 from public.products p where p.id=product_images.product_id and p.seller_id=(select auth.uid()))));
drop policy if exists product_images_upload on storage.objects;
drop policy if exists product_images_update on storage.objects;
drop policy if exists product_images_delete on storage.objects;
drop policy if exists product_images_select_own on storage.objects;
create policy product_images_upload on storage.objects for insert to authenticated with check (bucket_id='product-images' and (private.is_admin() or (storage.foldername(name))[1]=(select auth.uid())::text));
create policy product_images_select_own on storage.objects for select to authenticated using (bucket_id='product-images' and (private.is_admin() or (storage.foldername(name))[1]=(select auth.uid())::text));
create policy product_images_update on storage.objects for update to authenticated using (bucket_id='product-images' and (private.is_admin() or (storage.foldername(name))[1]=(select auth.uid())::text)) with check (bucket_id='product-images' and (private.is_admin() or (storage.foldername(name))[1]=(select auth.uid())::text));
create policy product_images_delete on storage.objects for delete to authenticated using (bucket_id='product-images' and (private.is_admin() or (storage.foldername(name))[1]=(select auth.uid())::text));