-- Phase 70: audit trail and admin observability.
create table if not exists public.audit_logs (
 id bigint generated by default as identity primary key,
 actor_id uuid references public.profiles(id) on delete set null,
 action text not null check (action ~ '^[a-z][a-z0-9_.-]{1,79}$'),
 entity_type text not null check (entity_type ~ '^[a-z][a-z0-9_.-]{1,79}$'),
 entity_id text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon, authenticated;
create or replace function public.record_audit_event(p_action text,p_entity_type text,p_entity_id text default null,p_metadata jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint; begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 insert into public.audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),lower(trim(p_action)),lower(trim(p_entity_type)),nullif(trim(p_entity_id),''),coalesce(p_metadata,'{}'::jsonb)) returning id into v_id; return v_id;
end $$;
create or replace function public.admin_list_audit_logs(p_limit integer default 100)
returns table(id bigint,actor_id uuid,actor_name text,action text,entity_type text,entity_id text,metadata jsonb,created_at timestamptz)
language sql stable security definer set search_path=public,pg_temp as $$
 select a.id,a.actor_id,p.full_name,a.action,a.entity_type,a.entity_id,a.metadata,a.created_at from public.audit_logs a left join public.profiles p on p.id=a.actor_id
 where exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='admin') order by a.created_at desc limit least(greatest(coalesce(p_limit,100),1),500);
$$;
create or replace function public.admin_observability_summary()
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object('generated_at',now(),'audit_events_24h',(select count(*) from public.audit_logs where created_at>=now()-interval '24 hours'),'analytics_events_24h',(select count(*) from public.analytics_events where created_at>=now()-interval '24 hours'),'shipments_total',(select count(*) from public.shipments),'failed_shipments',(select count(*) from public.shipments where status in ('failed','rto','cancelled','exception')),'open_returns',(select count(*) from public.return_requests where status in ('requested','approved','pickup_scheduled','picked_up','in_transit'))) where exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='admin');
$$;
revoke execute on function public.record_audit_event(text,text,text,jsonb) from public,anon,authenticated;
revoke execute on function public.admin_list_audit_logs(integer) from public,anon,authenticated;
revoke execute on function public.admin_observability_summary() from public,anon,authenticated;
grant execute on function public.record_audit_event(text,text,text,jsonb) to authenticated;
grant execute on function public.admin_list_audit_logs(integer) to authenticated;
grant execute on function public.admin_observability_summary() to authenticated;